const root=document.documentElement;
const storedTheme=localStorage.getItem('calc-theme'); if(storedTheme==='dark') root.dataset.theme='dark';
const storedLang=localStorage.getItem('calc-lang')||'en'; root.dataset.lang=storedLang; root.lang=storedLang;
function syncLangButtons(){document.querySelectorAll('[data-lang-toggle]').forEach(b=>b.textContent=(root.dataset.lang==='en'?'TH':'EN'))}
syncLangButtons();
document.addEventListener('click',e=>{
  const t=e.target.closest('[data-theme-toggle]'); if(t){const dark=root.dataset.theme==='dark'; if(dark) delete root.dataset.theme; else root.dataset.theme='dark'; localStorage.setItem('calc-theme',dark?'light':'dark'); window.dispatchEvent(new Event('calc-redraw'));}
  const l=e.target.closest('[data-lang-toggle]'); if(l){const next=root.dataset.lang==='en'?'th':'en'; root.dataset.lang=next; root.lang=next; localStorage.setItem('calc-lang',next); syncLangButtons(); renderSearch('');}
  const s=e.target.closest('.solution-btn'); if(s){s.closest('.problem')?.classList.toggle('open')}
});
// reveal animations
const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting)x.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
// active sidebar
const sections=[...document.querySelectorAll('.lesson-section[id]')];const links=[...document.querySelectorAll('.sidebar a[href^="#"]')];if(sections.length){const spy=new IntersectionObserver(es=>{es.filter(x=>x.isIntersecting).forEach(x=>{links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+x.target.id))})},{rootMargin:'-20% 0px -70%'});sections.forEach(s=>spy.observe(s))}
// search
const SEARCH=[
 {p:'index.html',id:'chapters',en:'Calculus overview',th:'ภาพรวมแคลคูลัส',dEn:'Limits, derivatives, integrals and core learning tools.',dTh:'ลิมิต อนุพันธ์ ปริพันธ์ และเครื่องมือการเรียนรู้'},
 {p:'limits.html',id:'intuition',en:'Limits — intuition',th:'ลิมิต — แนวคิด',dEn:'Approach, one-sided limits, continuity and indeterminate forms.',dTh:'การเข้าใกล้ ลิมิตด้านเดียว ความต่อเนื่อง และรูปไม่กำหนด'},
 {p:'limits.html',id:'laws',en:'Limit laws',th:'กฎของลิมิต',dEn:'Sum, product, quotient and power laws.',dTh:'กฎผลบวก ผลคูณ ผลหาร และยกกำลัง'},
 {p:'limits.html',id:'continuity',en:'Continuity',th:'ความต่อเนื่อง',dEn:'Three conditions for continuity at a point.',dTh:'เงื่อนไขสามข้อของความต่อเนื่อง'},
 {p:'derivatives.html',id:'definition',en:'Derivative definition',th:'นิยามอนุพันธ์',dEn:'Difference quotient and instantaneous rate of change.',dTh:'ผลต่างหารและอัตราการเปลี่ยนแปลงฉับพลัน'},
 {p:'derivatives.html',id:'rules',en:'Derivative rules',th:'กฎการหาอนุพันธ์',dEn:'Power, product, quotient and chain rules.',dTh:'กฎยกกำลัง ผลคูณ ผลหาร และลูกโซ่'},
 {p:'derivatives.html',id:'applications',en:'Derivative applications',th:'การประยุกต์อนุพันธ์',dEn:'Tangent lines, optimization and motion.',dTh:'เส้นสัมผัส การหาค่าสูงสุดต่ำสุด และการเคลื่อนที่'},
 {p:'derivatives.html',id:'calculator',en:'Derivative calculator',th:'เครื่องคำนวณอนุพันธ์',dEn:'Symbolic differentiation and graph preview.',dTh:'หาอนุพันธ์เชิงสัญลักษณ์และดูกราฟ'},
 {p:'integrals.html',id:'riemann',en:'Riemann sums',th:'ผลบวกรีมันน์',dEn:'Area as a limit of rectangle sums.',dTh:'พื้นที่ในรูปขีดจำกัดของผลบวกสี่เหลี่ยม'},
 {p:'integrals.html',id:'ftc',en:'Fundamental Theorem of Calculus',th:'ทฤษฎีบทมูลฐานของแคลคูลัส',dEn:'The bridge between derivatives and integrals.',dTh:'สะพานเชื่อมอนุพันธ์และปริพันธ์'},
 {p:'integrals.html',id:'techniques',en:'Integration techniques',th:'เทคนิคการอินทิเกรต',dEn:'Substitution and integration by parts.',dTh:'การแทนค่าและอินทิเกรตโดยส่วน'},
 {p:'integrals.html',id:'calculator',en:'Integral calculator',th:'เครื่องคำนวณปริพันธ์',dEn:'Symbolic antiderivatives and definite integrals.',dTh:'ปริพันธ์ไม่จำกัดเขตและปริพันธ์จำกัดเขต'},
 {p:'practice.html',id:'limits-practice',en:'Limit practice',th:'โจทย์ลิมิต',dEn:'Practice limits with step-by-step solutions.',dTh:'ฝึกโจทย์ลิมิตพร้อมเฉลยเป็นขั้นตอน'},
 {p:'practice.html',id:'derivatives-practice',en:'Derivative practice',th:'โจทย์อนุพันธ์',dEn:'Practice differentiation with solutions.',dTh:'ฝึกหาอนุพันธ์พร้อมเฉลย'},
 {p:'practice.html',id:'integrals-practice',en:'Integral practice',th:'โจทย์ปริพันธ์',dEn:'Practice integration with solutions.',dTh:'ฝึกอินทิเกรตพร้อมเฉลย'}
];
const overlay=document.getElementById('searchOverlay'),searchInput=document.getElementById('searchInput'),results=document.getElementById('searchResults');
function renderSearch(q=''){if(!results)return;const lang=root.dataset.lang;const term=q.trim().toLowerCase();const found=SEARCH.filter(x=>!term||[x.en,x.th,x.dEn,x.dTh].join(' ').toLowerCase().includes(term));results.innerHTML=found.length?found.map(x=>`<a class="search-result" href="${x.p}#${x.id}"><strong>${lang==='th'?x.th:x.en}</strong><span>${lang==='th'?x.dTh:x.dEn}</span></a>`).join(''):`<div class="search-empty">${lang==='th'?'ไม่พบหัวข้อ':'No matching topics'}</div>`}
function openSearch(){if(!overlay)return;overlay.classList.add('open');renderSearch('');setTimeout(()=>searchInput?.focus(),40)}function closeSearch(){overlay?.classList.remove('open')}
document.querySelectorAll('[data-search-open]').forEach(b=>b.addEventListener('click',openSearch));document.getElementById('searchClose')?.addEventListener('click',closeSearch);searchInput?.addEventListener('input',e=>renderSearch(e.target.value));overlay?.addEventListener('click',e=>{if(e.target===overlay)closeSearch()});window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')closeSearch()});
// math helpers
function mathEval(expr,x){if(window.math){try{return math.evaluate(expr,{x})}catch{return NaN}}return NaN}
function setupCanvas(c,ratio=.58){const dpr=devicePixelRatio||1,r=c.getBoundingClientRect(),w=r.width,h=w*ratio;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w,h}}
function css(n){return getComputedStyle(root).getPropertyValue(n).trim()}
function axes(ctx,w,h,xp,yp,x0,x1,y0,y1){ctx.clearRect(0,0,w,h);ctx.strokeStyle=css('--line');ctx.lineWidth=1;for(let x=Math.ceil(x0);x<=x1;x++){ctx.beginPath();ctx.moveTo(xp(x),0);ctx.lineTo(xp(x),h);ctx.stroke()}for(let y=Math.ceil(y0);y<=y1;y++){ctx.beginPath();ctx.moveTo(0,yp(y));ctx.lineTo(w,yp(y));ctx.stroke()}ctx.strokeStyle=css('--muted');ctx.beginPath();ctx.moveTo(0,yp(0));ctx.lineTo(w,yp(0));ctx.stroke();ctx.beginPath();ctx.moveTo(xp(0),0);ctx.lineTo(xp(0),h);ctx.stroke()}
function plot(canvas,expr,{xMin=-5,xMax=5,yMin=-5,yMax=5}={}){if(!canvas)return;const {ctx,w,h}=setupCanvas(canvas),xp=x=>(x-xMin)/(xMax-xMin)*w,yp=y=>h-(y-yMin)/(yMax-yMin)*h;axes(ctx,w,h,xp,yp,xMin,xMax,yMin,yMax);ctx.strokeStyle=css('--accent');ctx.lineWidth=2.4;ctx.beginPath();let started=false;for(let i=0;i<=700;i++){const x=xMin+(xMax-xMin)*i/700,y=mathEval(expr,x);if(!Number.isFinite(y)||Math.abs(y)>1e5){started=false;continue}const px=xp(x),py=yp(y);if(!started){ctx.moveTo(px,py);started=true}else ctx.lineTo(px,py)}ctx.stroke()}
const graphCanvas=document.getElementById('functionGraph'),graphInput=document.getElementById('graphExpr');function drawFunction(){if(graphCanvas&&graphInput)plot(graphCanvas,graphInput.value||'sin(x)',{xMin:-6,xMax:6,yMin:-5,yMax:5})}document.getElementById('graphDraw')?.addEventListener('click',drawFunction);graphInput?.addEventListener('keydown',e=>{if(e.key==='Enter')drawFunction()});
// derivative tangent
const dCanvas=document.getElementById('derivativeCanvas'),dSlider=document.getElementById('xSlider');function drawDerivativeDemo(){if(!dCanvas||!dSlider)return;const {ctx,w,h}=setupCanvas(dCanvas),xMin=-3,xMax=3,yMin=-1,yMax=7,xp=x=>(x-xMin)/(xMax-xMin)*w,yp=y=>h-(y-yMin)/(yMax-yMin)*h;axes(ctx,w,h,xp,yp,xMin,xMax,yMin,yMax);ctx.strokeStyle=css('--accent');ctx.lineWidth=2.5;ctx.beginPath();for(let i=0;i<=500;i++){const x=xMin+(xMax-xMin)*i/500,y=x*x;i?ctx.lineTo(xp(x),yp(y)):ctx.moveTo(xp(x),yp(y))}ctx.stroke();const x0=+dSlider.value,y0=x0*x0,m=2*x0;ctx.strokeStyle=css('--ink');ctx.lineWidth=1.8;ctx.beginPath();ctx.moveTo(xp(xMin),yp(y0+m*(xMin-x0)));ctx.lineTo(xp(xMax),yp(y0+m*(xMax-x0)));ctx.stroke();ctx.fillStyle=css('--ink');ctx.beginPath();ctx.arc(xp(x0),yp(y0),5,0,Math.PI*2);ctx.fill();document.getElementById('xValue').textContent=x0.toFixed(1);document.getElementById('slopeValue').textContent=m.toFixed(2)}dSlider?.addEventListener('input',drawDerivativeDemo);
// riemann
const rCanvas=document.getElementById('riemannCanvas'),rSlider=document.getElementById('nSlider');function drawRiemann(){if(!rCanvas||!rSlider)return;const {ctx,w,h}=setupCanvas(rCanvas),xMin=-.3,xMax=2.3,yMin=-.5,yMax=5.7,xp=x=>(x-xMin)/(xMax-xMin)*w,yp=y=>h-(y-yMin)/(yMax-yMin)*h;axes(ctx,w,h,xp,yp,xMin,xMax,yMin,yMax);const n=+rSlider.value,a=0,b=2,dx=(b-a)/n;let sum=0;ctx.fillStyle=css('--accent-soft');ctx.strokeStyle=css('--accent');for(let i=0;i<n;i++){const x=a+i*dx,m=x+dx/2,y=m*m+1;sum+=y*dx;const L=xp(x),R=xp(x+dx),T=yp(y),B=yp(0);ctx.fillRect(L,T,R-L,B-T);ctx.strokeRect(L,T,R-L,B-T)}ctx.strokeStyle=css('--ink');ctx.lineWidth=2.3;ctx.beginPath();for(let i=0;i<=400;i++){const x=a+(b-a)*i/400,y=x*x+1;i?ctx.lineTo(xp(x),yp(y)):ctx.moveTo(xp(x),yp(y))}ctx.stroke();document.getElementById('nValue').textContent=n;document.getElementById('areaValue').textContent=sum.toFixed(4)}rSlider?.addEventListener('input',drawRiemann);
// calculators (Nerdamer preferred)
function calcDerivative(){const inp=document.getElementById('derivExpr'),out=document.getElementById('derivOut');if(!inp||!out)return;const e=inp.value.trim();try{let ans;if(window.nerdamer)ans=nerdamer.diff(e,'x').toTeX();else if(window.math)ans=math.derivative(e,'x').toTex();else throw Error('engine');out.innerHTML=`\\[${ans}\\]`;window.MathJax?.typesetPromise?.([out]);const c=document.getElementById('calcGraph');if(c)plot(c,e,{xMin:-5,xMax:5,yMin:-6,yMax:6})}catch{out.textContent=root.dataset.lang==='th'?'ตรวจรูปแบบสมการอีกครั้ง เช่น x^3+sin(x)':'Check the expression, e.g. x^3+sin(x)'}}
document.getElementById('derivCalcBtn')?.addEventListener('click',calcDerivative);
function simpson(expr,a,b,n=600){if(n%2)n++;const h=(b-a)/n;let s=mathEval(expr,a)+mathEval(expr,b);for(let i=1;i<n;i++)s+=(i%2?4:2)*mathEval(expr,a+i*h);return s*h/3}
function calcIntegral(){const inp=document.getElementById('intExpr'),out=document.getElementById('intOut');if(!inp||!out)return;const e=inp.value.trim(),a=+document.getElementById('intA').value,b=+document.getElementById('intB').value;try{let symbolic='';if(window.nerdamer)symbolic=nerdamer.integrate(e,'x').toTeX();let numeric=Number.isFinite(a)&&Number.isFinite(b)?simpson(e,a,b):NaN;out.innerHTML=`${symbolic?`<div>\\[\\int ${nerdamer(e).toTeX()}\\,dx=${symbolic}+C\\]</div>`:''}${Number.isFinite(numeric)?`<div><strong>${root.dataset.lang==='th'?'ค่าปริพันธ์จำกัดเขต':'Definite integral'}:</strong> ${numeric.toFixed(8)}</div>`:''}`;window.MathJax?.typesetPromise?.([out]);const c=document.getElementById('intGraph');if(c)plot(c,e,{xMin:-5,xMax:5,yMin:-6,yMax:6})}catch{out.textContent=root.dataset.lang==='th'?'ตรวจสมการและขอบเขตอีกครั้ง':'Check the expression and bounds'}}
document.getElementById('intCalcBtn')?.addEventListener('click',calcIntegral);
function redraw(){drawFunction();drawDerivativeDemo();drawRiemann();const de=document.getElementById('derivExpr');if(document.getElementById('calcGraph')&&de)plot(document.getElementById('calcGraph'),de.value||'x^3-3*x',{xMin:-5,xMax:5,yMin:-6,yMax:6});const ie=document.getElementById('intExpr');if(document.getElementById('intGraph')&&ie)plot(document.getElementById('intGraph'),ie.value||'sin(x)',{xMin:-5,xMax:5,yMin:-6,yMax:6})}
window.addEventListener('load',redraw);window.addEventListener('resize',redraw);window.addEventListener('calc-redraw',redraw);
