const fs=require('node:fs');
const {JSDOM}=require('jsdom');
const clean=s=>s.replace(/\s+/g,' ').trim();
const localized=(el,lang)=>{const c=el.cloneNode(true);c.querySelectorAll(lang==='en'?'.lang-th':'.lang-en').forEach(n=>n.remove());return clean(c.textContent);};
const index=[];
for(const page of ['index','limits','derivatives','integrals','practice']){
  const dom=new JSDOM(fs.readFileSync(page+'.html','utf8')),d=dom.window.document;
  for(const el of d.querySelectorAll(page==='index'?'#chapters,#function-lab':'.lesson-section[id],.problem[id]')){
    const heading=el.querySelector('h2,h3');if(!heading)continue;
    const copy=el.cloneNode(true);copy.querySelectorAll('.problem,canvas,svg,button,select,input,script').forEach(n=>n.remove());
    // Each exercise has its own result; section previews do not swallow nested titles.
    const source=el.matches('.problem')?el:copy;
    index.push({url:`${page}.html#${el.id}`,en:localized(heading,'en'),th:localized(heading,'th'),text:clean(source.textContent),previewEn:localized(source,'en').slice(0,180),previewTh:localized(source,'th').slice(0,180)});
  }
  dom.window.close();
}
fs.writeFileSync('search-index.js','// Generated by node scripts/build-search.cjs; searchable without a network request.\nwindow.SEARCH_INDEX = '+JSON.stringify(index,null,2)+';\n');
console.log(`Indexed ${index.length} lesson and practice destinations.`);
