// Generated by python3 scripts/build-search.py; all content stays searchable offline.
window.SEARCH_INDEX = [
  {
    "url": "index.html#chapters",
    "en": "Course overview and function grapher",
    "th": "ภาพรวมบทเรียนและเครื่องพล็อตกราฟ",
    "text": "limits derivatives integrals functions graph plot ลิมิต อนุพันธ์ ปริพันธ์ กราฟ ฟังก์ชัน",
    "previewEn": "Start here: chapters, prerequisites, and a function graphing laboratory.",
    "previewTh": "เริ่มที่นี่: บทเรียน พื้นฐาน และห้องทดลองกราฟฟังก์ชัน"
  },
  {
    "url": "index.html#function-lab",
    "en": "Function graphing laboratory",
    "th": "ห้องทดลองกราฟฟังก์ชัน",
    "text": "function grapher plot sin cos tan x graph domain พล็อตกราฟ โดเมน ฟังก์ชัน",
    "previewEn": "Plot an expression in x and inspect its real domain.",
    "previewTh": "พล็อตนิพจน์ที่มี x และสำรวจโดเมนค่าจริง"
  },
  {
    "url": "limits.html#intuition",
    "en": "1. Intuition and notation One-sided limits",
    "th": "1. แนวคิดและสัญลักษณ์ ลิมิตด้านเดียว",
    "text": "1. Intuition and notation 1. แนวคิดและสัญลักษณ์ Definition นิยาม $$\\lim_{x\\to a}f(x)=L$$ means that $f(x)$ can be made arbitrarily close to $L$ by choosing $x$ sufficiently close to $a$ (with $x\\neq a$). หมายความว่าเราสามารถทำให้ $f(x)$ ใกล้ $L$ ได้มากเท่าใดก็ได้ โดยเลือก $x$ ให้ใกล้ $a$ มากพอ โดยไม่จำเป็นต้องให้ $x=a$ A limit concerns nearby behavior, not necessarily the value at the point. Therefore $f(a)$ may be different from the limit, or even undefined. ลิมิตสนใจพฤติกรรม “รอบ ๆ จุด” ไม่จำเป็นต้องสนใจค่าที่จุดนั้นโดยตรง ดังนั้น $f(a)$ อาจไม่เท่ากับลิมิต หรืออาจนิยามไม่ได้เลย Example ตัวอย่าง $$\\lim_{x\\to2}\\frac{x^2-4}{x-2}$$ Factor $x^2-4=(x-2)(x+2)$, cancel the common factor for $x\\ne2$, then evaluate $x+2$ at $x=2$. The limit is $4$. แยกตัวประกอบ $x^2-4=(x-2)(x+2)$ แล้วตัดตัวประกอบร่วมเมื่อ $x\\ne2$ จะเหลือ $x+2$ ดังนั้นลิมิตเท่ากับ $4$ One-sided limits ลิมิตด้านเดียว $$\\lim_{x\\to a^-}f(x),\\qquad \\lim_{x\\to a^+}f(x)$$ The two-sided limit exists only when the left-hand and right-hand limits both exist and are equal. ลิมิตสองด้านจะมีอยู่ก็ต่อเมื่อลิมิตด้านซ้ายและด้านขวามีอยู่และมีค่าเท่ากัน",
    "previewEn": "Definition $$\\lim_{x\\to a}f(x)=L$$ means that $f(x)$ can be made arbitrarily close to $L$ by choosing $x$ sufficiently close to $a$ (with $x\\neq a$). A limit co",
    "previewTh": "นิยาม หมายความว่าเราสามารถทำให้ $f(x)$ ใกล้ $L$ ได้มากเท่าใดก็ได้ โดยเลือก $x$ ให้ใกล้ $a$ มากพอ โดยไม่จำเป็นต้องให้ $x=a$ ลิมิตสนใจพฤติกรรม “รอบ ๆ จุด” ไม่จำเป"
  },
  {
    "url": "limits.html#laws",
    "en": "2. Limit laws",
    "th": "2. กฎของลิมิต",
    "text": "2. Limit laws 2. กฎของลิมิต If $\\lim f(x)=L$ and $\\lim g(x)=M$, then limits behave algebraically in familiar ways. ถ้า $\\lim f(x)=L$ และ $\\lim g(x)=M$ เราสามารถจัดการลิมิตเชิงพีชคณิตได้คล้ายกับตัวเลขทั่วไป Sum ผลบวก $$\\lim(f+g)=L+M$$ Product ผลคูณ $$\\lim(fg)=LM$$ Quotient ผลหาร $$\\lim\\frac{f}{g}=\\frac{L}{M},\\;M\\ne0$$ Power ยกกำลัง $$\\lim[f(x)]^n=L^n$$ Always try direct substitution first. If it gives a finite value, continuity often finishes the problem immediately. เริ่มจากแทนค่าตรง ๆ ก่อนเสมอ ถ้าได้ค่าจำกัด มักจบโจทย์ได้ทันทีจากความต่อเนื่อง These algebraic laws assume finite limits L and M. In the power law above, n is a positive integer. For roots or general real powers, also check the real domain and continuity of the outer function. กฎพีชคณิตนี้สมมติว่า L และ M เป็นลิมิตจำกัด ในกฎยกกำลังข้างต้น n เป็นจำนวนเต็มบวก สำหรับรากหรือกำลังจริงทั่วไป ต้องตรวจโดเมนค่าจริงและความต่อเนื่องของฟังก์ชันชั้นนอกด้วย",
    "previewEn": "If $\\lim f(x)=L$ and $\\lim g(x)=M$, then limits behave algebraically in familiar ways. Sum $$\\lim(f+g)=L+M$$ Product $$\\lim(fg)=LM$$ Quotient $$\\lim\\frac{f}{g}=",
    "previewTh": "ถ้า $\\lim f(x)=L$ และ $\\lim g(x)=M$ เราสามารถจัดการลิมิตเชิงพีชคณิตได้คล้ายกับตัวเลขทั่วไป ผลบวก ผลคูณ ผลหาร ยกกำลัง เริ่มจากแทนค่าตรง ๆ ก่อนเสมอ ถ้าได้ค่าจำกัด"
  },
  {
    "url": "limits.html#indeterminate",
    "en": "3. Indeterminate forms Important trigonometric limit",
    "th": "3. รูปไม่กำหนด ลิมิตตรีโกณมิติสำคัญ",
    "text": "3. Indeterminate forms 3. รูปไม่กำหนด Expressions such as $0/0$ and $\\infty/\\infty$ do not determine a limit by themselves. They signal that simplification or another theorem is needed. รูปอย่าง $0/0$ หรือ $\\infty/\\infty$ ไม่ได้บอกคำตอบของลิมิต แต่เป็นสัญญาณว่าต้องจัดรูปหรือใช้ทฤษฎีเพิ่มเติม Factoring แยกตัวประกอบ $$\\lim_{x\\to3}\\frac{x^2-9}{x-3}=\\lim_{x\\to3}(x+3)=6$$ Rationalizing คูณด้วยพจน์สังยุค $$\\lim_{x\\to0}\\frac{\\sqrt{1+x}-1}{x}=\\frac12$$ Important trigonometric limit ลิมิตตรีโกณมิติสำคัญ $$\\lim_{x\\to0}\\frac{\\sin x}{x}=1$$ This result is central to differentiating sine and cosine. ผลลัพธ์นี้เป็นหัวใจสำคัญในการหาอนุพันธ์ของ sine และ cosine",
    "previewEn": "Expressions such as $0/0$ and $\\infty/\\infty$ do not determine a limit by themselves. They signal that simplification or another theorem is needed. Factoring $$",
    "previewTh": "รูปอย่าง $0/0$ หรือ $\\infty/\\infty$ ไม่ได้บอกคำตอบของลิมิต แต่เป็นสัญญาณว่าต้องจัดรูปหรือใช้ทฤษฎีเพิ่มเติม แยกตัวประกอบ คูณด้วยพจน์สังยุค ผลลัพธ์นี้เป็นหัวใจสำค"
  },
  {
    "url": "limits.html#continuity",
    "en": "4. Continuity",
    "th": "4. ความต่อเนื่อง",
    "text": "4. Continuity 4. ความต่อเนื่อง A function $f$ is continuous at $x=a$ when all three conditions hold: ฟังก์ชัน $f$ ต่อเนื่องที่ $x=a$ เมื่อครบทั้งสามเงื่อนไข: Both f(a) and the limit must exist, and their values must agree. ทั้ง f(a) และลิมิตต้องมีค่า และค่าทั้งสองต้องเท่ากัน $$\\lim_{x\\to a}f(x)=f(a)$$ Intermediate Value Theorem ทฤษฎีบทค่าระหว่างกลาง If $f$ is continuous on $[a,b]$ and $N$ lies between $f(a)$ and $f(b)$, then there is some $c\\in[a,b]$ such that $f(c)=N$. ถ้า $f$ ต่อเนื่องบน $[a,b]$ และ $N$ อยู่ระหว่าง $f(a)$ กับ $f(b)$ จะมีอย่างน้อยหนึ่งค่า $c\\in[a,b]$ ที่ทำให้ $f(c)=N$",
    "previewEn": "A function $f$ is continuous at $x=a$ when all three conditions hold: Both f(a) and the limit must exist, and their values must agree. $$\\lim_{x\\to a}f(x)=f(a)$",
    "previewTh": "ฟังก์ชัน $f$ ต่อเนื่องที่ $x=a$ เมื่อครบทั้งสามเงื่อนไข: ทั้ง f(a) และลิมิตต้องมีค่า และค่าทั้งสองต้องเท่ากัน ทฤษฎีบทค่าระหว่างกลาง ถ้า $f$ ต่อเนื่องบน $[a,b]$ "
  },
  {
    "url": "limits.html#infinity",
    "en": "5. Limits at infinity",
    "th": "5. ลิมิตเมื่อ $x\\to\\infty$",
    "text": "5. Limits at infinity 5. ลิมิตเมื่อ $x\\to\\infty$ For rational functions, compare the highest powers in numerator and denominator. สำหรับฟังก์ชันตรรกยะ ให้เปรียบเทียบดีกรีสูงสุดของตัวเศษและตัวส่วน degree top < bottom ดีกรีเศษน้อยกว่าส่วน $$\\lim_{x\\to\\infty}\\frac{x}{x^2+1}=0$$ same degree ดีกรีเท่ากัน $$\\lim_{x\\to\\infty}\\frac{3x^2+1}{2x^2-5}=\\frac32$$ Horizontal asymptotes describe end behavior; they do not forbid the graph from crossing the asymptote. เส้นกำกับแนวนอนอธิบายพฤติกรรมเมื่อ $|x|$ ใหญ่มาก แต่กราฟยังสามารถตัดเส้นกำกับนั้นได้",
    "previewEn": "For rational functions, compare the highest powers in numerator and denominator. degree top < bottom $$\\lim_{x\\to\\infty}\\frac{x}{x^2+1}=0$$ same degree $$\\lim_{",
    "previewTh": "สำหรับฟังก์ชันตรรกยะ ให้เปรียบเทียบดีกรีสูงสุดของตัวเศษและตัวส่วน ดีกรีเศษน้อยกว่าส่วน ดีกรีเท่ากัน เส้นกำกับแนวนอนอธิบายพฤติกรรมเมื่อ $|x|$ ใหญ่มาก แต่กราฟยังส"
  },
  {
    "url": "limits.html#epsilon-delta",
    "en": "6. The precise ε–δ definition",
    "th": "6. นิยามเอปไซลอน–เดลตา",
    "text": "6. The precise ε–δ definition 6. นิยามเอปไซลอน–เดลตา Intuition becomes a theorem when “close” has a measurable meaning. The output tolerance ε is chosen first; you must then find an input tolerance δ that works for every point in the punctured neighborhood. แนวคิดเรื่อง “ใกล้” จะแม่นยำเมื่อวัดได้ เรากำหนดความคลาดเคลื่อนของผลลัพธ์ ε ก่อน แล้วต้องหา δ ที่ทำให้เงื่อนไขเป็นจริงสำหรับทุกจุดรอบจุดเป้าหมาย ยกเว้นจุดนั้นเอง Formal definition นิยามอย่างเป็นทางการ $$\\forall\\varepsilon>0\\;\\exists\\delta>0:\\quad 0<|x-a|<\\delta\\implies|f(x)-L|<\\varepsilon$$ Here x belongs to the domain of f, and a must be an accumulation point of that domain. δ may depend on ε and a, but not on x. ในที่นี้ x ต้องอยู่ในโดเมนของ f และ a ต้องเป็นจุดสะสมของโดเมน δ ขึ้นกับ ε และ a ได้ แต่ต้องไม่ขึ้นกับ x Proof: a linear function พิสูจน์: ฟังก์ชันเชิงเส้น Prove that the limit of 3x + 1 at x = 2 is 7. Let ε > 0 be arbitrary and choose δ = ε/3. พิสูจน์ว่าลิมิตของ 3x + 1 เมื่อ x เข้าใกล้ 2 เท่ากับ 7 ให้ ε > 0 เป็นจำนวนใด ๆ แล้วเลือก δ = ε/3 $$0<|x-2|<\\delta\\quad\\Longrightarrow\\quad |(3x+1)-7|=3|x-2|<3\\delta=\\varepsilon$$ This proves the statement for every positive tolerance, not just for a few numerical samples. จึงพิสูจน์ได้สำหรับความคลาดเคลื่อนบวกทุกค่า ไม่ใช่เพียงตัวอย่างเชิงตัวเลขบางค่า Proof: a nonlinear function พิสูจน์: ฟังก์ชันไม่เชิงเส้น To prove the limit of x² at 2 is 4, factor |x² − 4| = |x − 2||x + 2|. First require |x − 2| < 1, so |x + 2| < 5. Choose δ = min(1, ε/5). Then the error is less than 5δ ≤ ε. เพื่อพิสูจน์ว่าลิมิตของ x² ที่ 2 เท่ากับ 4 ให้แยก |x² − 4| = |x − 2||x + 2| กำหนด |x − 2| < 1 ก่อน จึงได้ |x + 2| < 5 แล้วเลือก δ = min(1, ε/5) ความคลาดเคลื่อนจึงน้อยกว่า 5δ ≤ ε",
    "previewEn": "Intuition becomes a theorem when “close” has a measurable meaning. The output tolerance ε is chosen first; you must then find an input tolerance δ that works fo",
    "previewTh": "แนวคิดเรื่อง “ใกล้” จะแม่นยำเมื่อวัดได้ เรากำหนดความคลาดเคลื่อนของผลลัพธ์ ε ก่อน แล้วต้องหา δ ที่ทำให้เงื่อนไขเป็นจริงสำหรับทุกจุดรอบจุดเป้าหมาย ยกเว้นจุดนั้นเอ"
  },
  {
    "url": "limits.html#squeeze",
    "en": "7. Squeeze theorem and oscillation",
    "th": "7. ทฤษฎีบทบีบและการแกว่ง",
    "text": "7. Squeeze theorem and oscillation 7. ทฤษฎีบทบีบและการแกว่ง Squeeze theorem ทฤษฎีบทบีบ If g(x) ≤ f(x) ≤ h(x) near a (except possibly at a), and both bounding functions tend to L, then f(x) tends to L. ถ้า g(x) ≤ f(x) ≤ h(x) ในบริเวณใกล้ a (อาจยกเว้นที่ a) และฟังก์ชันที่บีบทั้งสองเข้าใกล้ L แล้ว f(x) จะเข้าใกล้ L เช่นกัน $$-x^2\\le x^2\\sin(1/x)\\le x^2\\quad\\Longrightarrow\\quad\\lim_{x\\to0}x^2\\sin(1/x)=0$$ The oscillation of sin(1/x) never settles, but multiplying by x² squeezes its amplitude to zero. By itself, sin(1/x) has no limit: sequences approaching zero can produce values 1 and −1. sin(1/x) แกว่งไม่หยุด แต่เมื่อคูณด้วย x² ขนาดการแกว่งจะถูกบีบเข้าหาศูนย์ ส่วน sin(1/x) เพียงอย่างเดียวไม่มีลิมิต เพราะเลือกลำดับที่เข้าใกล้ศูนย์แล้วได้ค่า 1 และ −1 ได้ Radians are essential ต้องใช้เรเดียน The limit sin(x)/x = 1 uses radians. Replacing x by kx gives sin(kx)/x → k. This result can be proved geometrically by squeezing, without assuming the derivative of sine. ลิมิต sin(x)/x = 1 ใช้เมื่อวัดมุมเป็นเรเดียน เมื่อแทน x ด้วย kx จะได้ sin(kx)/x → k สามารถพิสูจน์ด้วยเรขาคณิตและทฤษฎีบทบีบ โดยไม่ต้องสมมติอนุพันธ์ของ sine ก่อน",
    "previewEn": "Squeeze theorem If g(x) ≤ f(x) ≤ h(x) near a (except possibly at a), and both bounding functions tend to L, then f(x) tends to L. $$-x^2\\le x^2\\sin(1/x)\\le x^2\\",
    "previewTh": "ทฤษฎีบทบีบ ถ้า g(x) ≤ f(x) ≤ h(x) ในบริเวณใกล้ a (อาจยกเว้นที่ a) และฟังก์ชันที่บีบทั้งสองเข้าใกล้ L แล้ว f(x) จะเข้าใกล้ L เช่นกัน sin(1/x) แกว่งไม่หยุด แต่เมื"
  },
  {
    "url": "limits.html#lhopital",
    "en": "8. L’Hôpital’s rule and its limits",
    "th": "8. กฎโลปิตาลและเงื่อนไขการใช้",
    "text": "8. L’Hôpital’s rule and its limits 8. กฎโลปิตาลและเงื่อนไขการใช้ Check hypotheses first ตรวจเงื่อนไขก่อนใช้ Suppose f and g are differentiable on a punctured one-sided interval near a, g′ is nonzero there, and f/g has form 0/0 or ∞/∞. If f′/g′ tends to a finite or infinite limit, then f/g has that same limit. Apply each side separately for a two-sided limit. สมมติ f และ g หาอนุพันธ์ได้ในช่วงด้านเดียวใกล้ a ที่ยกเว้นจุด a และ g′ ไม่เป็นศูนย์ในช่วงนั้น ถ้า f/g อยู่ในรูป 0/0 หรือ ∞/∞ และ f′/g′ มีลิมิตเป็นจำนวนจำกัดหรืออนันต์ แล้ว f/g มีลิมิตเดียวกัน สำหรับลิมิตสองด้านต้องตรวจทั้งสองด้าน $$\\lim_{x\\to0}\\frac{e^x-1-x}{x^2}=\\lim_{x\\to0}\\frac{e^x-1}{2x}=\\lim_{x\\to0}\\frac{e^x}{2}=\\frac12$$ Both applications above still have form 0/0. The rule differentiates numerator and denominator separately; it does not use the quotient rule. It also does not apply to 1/0. Rewrite products, differences, and powers into an eligible quotient first. ทั้งสองครั้งข้างต้นยังอยู่ในรูป 0/0 กฎนี้หาอนุพันธ์ตัวเศษและตัวส่วนแยกกัน ไม่ใช่ใช้กฎผลหาร และใช้กับ 1/0 ไม่ได้ สำหรับผลคูณ ผลต่าง หรือเลขยกกำลัง ต้องจัดให้อยู่ในรูปผลหารที่เข้าเงื่อนไขก่อน A power limit ลิมิตของเลขยกกำลัง For x > 0 let y = xˣ. Then ln y = x ln x = ln x/(1/x). L’Hôpital gives a limit of 0 for ln y, so y tends to e⁰ = 1 as x approaches zero from the right. เมื่อ x > 0 ให้ y = xˣ จะได้ ln y = x ln x = ln x/(1/x) ใช้กฎโลปิตาลได้ลิมิตของ ln y เท่ากับ 0 ดังนั้น y เข้าใกล้ e⁰ = 1 เมื่อ x เข้าใกล้ศูนย์จากด้านขวา",
    "previewEn": "Check hypotheses first Suppose f and g are differentiable on a punctured one-sided interval near a, g′ is nonzero there, and f/g has form 0/0 or ∞/∞. If f′/g′ t",
    "previewTh": "ตรวจเงื่อนไขก่อนใช้ สมมติ f และ g หาอนุพันธ์ได้ในช่วงด้านเดียวใกล้ a ที่ยกเว้นจุด a และ g′ ไม่เป็นศูนย์ในช่วงนั้น ถ้า f/g อยู่ในรูป 0/0 หรือ ∞/∞ และ f′/g′ มีลิม"
  },
  {
    "url": "limits.html#limit-lab",
    "en": "9. Laboratory: approaching a point",
    "th": "9. ห้องทดลอง: การเข้าใกล้จุด",
    "text": "9. Laboratory: approaching a point 9. ห้องทดลอง: การเข้าใกล้จุด Compare a removable hole with a jump. Move the distance slider toward zero and inspect both sides. Numerical evidence suggests behavior; the definition or a theorem proves it. เปรียบเทียบจุดขาดที่เติมเต็มได้กับการกระโดด เลื่อนระยะเข้าหาศูนย์แล้วสังเกตทั้งสองด้าน ข้อมูลเชิงตัวเลขช่วยคาดการณ์ แต่ต้องใช้นิยามหรือทฤษฎีบทเพื่อพิสูจน์ Example ตัวอย่าง Removable hole: (x²−4)/(x−2) Jump: −1 on the left, 1 on the right Closeness (powers of 10) ความใกล้ (กำลังของ 10) Left and right approach to a limit การเข้าใกล้ลิมิตจากซ้ายและขวา",
    "previewEn": "Compare a removable hole with a jump. Move the distance slider toward zero and inspect both sides. Numerical evidence suggests behavior; the definition or a the",
    "previewTh": "เปรียบเทียบจุดขาดที่เติมเต็มได้กับการกระโดด เลื่อนระยะเข้าหาศูนย์แล้วสังเกตทั้งสองด้าน ข้อมูลเชิงตัวเลขช่วยคาดการณ์ แต่ต้องใช้นิยามหรือทฤษฎีบทเพื่อพิสูจน์ ตัวอย"
  },
  {
    "url": "derivatives.html#definition",
    "en": "1. Definition from a limit",
    "th": "1. นิยามจากลิมิต",
    "text": "1. Definition from a limit 1. นิยามจากลิมิต $$f'(x)=\\lim_{h\\to0}\\frac{f(x+h)-f(x)}{h}$$ The fraction is an average rate of change over a small interval. Letting $h\\to0$ produces the instantaneous rate. เศษส่วนนี้คืออัตราการเปลี่ยนแปลงเฉลี่ยในช่วงเล็ก ๆ และเมื่อให้ $h\\to0$ จะได้อัตราการเปลี่ยนแปลงฉับพลัน From first principles จากนิยาม For $f(x)=x^2$: สำหรับ $f(x)=x^2$: $$\\frac{(x+h)^2-x^2}{h}=\\frac{2xh+h^2}{h}=2x+h$$ $$f'(x)=\\lim_{h\\to0}(2x+h)=2x$$ Differentiability implies continuity, but continuity does not guarantee differentiability. Example: $|x|$ is continuous at $0$ but has a corner there. ถ้าหาอนุพันธ์ได้ย่อมต่อเนื่อง แต่ความต่อเนื่องไม่ได้รับประกันว่าจะหาอนุพันธ์ได้ เช่น $|x|$ ต่อเนื่องที่ 0 แต่มีมุมแหลม",
    "previewEn": "$$f'(x)=\\lim_{h\\to0}\\frac{f(x+h)-f(x)}{h}$$ The fraction is an average rate of change over a small interval. Letting $h\\to0$ produces the instantaneous rate. Fr",
    "previewTh": "เศษส่วนนี้คืออัตราการเปลี่ยนแปลงเฉลี่ยในช่วงเล็ก ๆ และเมื่อให้ $h\\to0$ จะได้อัตราการเปลี่ยนแปลงฉับพลัน จากนิยาม สำหรับ $f(x)=x^2$: ถ้าหาอนุพันธ์ได้ย่อมต่อเนื่อง"
  },
  {
    "url": "derivatives.html#rules",
    "en": "2. Differentiation rules Common derivatives",
    "th": "2. กฎการหาอนุพันธ์ อนุพันธ์พื้นฐานที่ควรรู้",
    "text": "2. Differentiation rules 2. กฎการหาอนุพันธ์ Power rule กฎยกกำลัง $$\\frac{d}{dx}x^n=nx^{n-1}$$ Product rule กฎผลคูณ $$\\frac{d}{dx}(uv)=u'v+uv'$$ Quotient rule กฎผลหาร $$\\left(\\frac uv\\right)'=\\frac{u'v-uv'}{v^2}$$ Chain rule กฎลูกโซ่ $$\\frac{d}{dx}f(g(x))=f'(g(x))g'(x)$$ Common derivatives อนุพันธ์พื้นฐานที่ควรรู้ $$(e^x)'=e^x,\\qquad (\\ln x)'=\\frac1x$$ $$(\\sin x)'=\\cos x,\\qquad (\\cos x)'=-\\sin x$$ $$(\\tan x)'=\\sec^2x$$ $$(a^x)'=a^x\\ln a$$ Chain rule example ตัวอย่างกฎลูกโซ่ $$y=(3x^2+1)^5$$ $$y'=5(3x^2+1)^4\\cdot6x=30x(3x^2+1)^4$$ Apply rules only where the functions are differentiable. Quotients require a nonzero denominator; ln x requires x > 0; aˣ assumes a > 0. For a general real exponent n, the power rule holds on x > 0 and on other real intervals where the power is defined and differentiable. ใช้กฎเมื่อฟังก์ชันหาอนุพันธ์ได้ กฎผลหารต้องมีตัวส่วนไม่เป็นศูนย์ ln x ต้องมี x > 0 และ aˣ สมมติ a > 0 สำหรับกำลังจริง n กฎยกกำลังใช้บน x > 0 และช่วงค่าจริงอื่นที่ฟังก์ชันนิยามและหาอนุพันธ์ได้",
    "previewEn": "Power rule $$\\frac{d}{dx}x^n=nx^{n-1}$$ Product rule $$\\frac{d}{dx}(uv)=u'v+uv'$$ Quotient rule $$\\left(\\frac uv\\right)'=\\frac{u'v-uv'}{v^2}$$ Chain rule $$\\fra",
    "previewTh": "กฎยกกำลัง กฎผลคูณ กฎผลหาร กฎลูกโซ่ ตัวอย่างกฎลูกโซ่ ใช้กฎเมื่อฟังก์ชันหาอนุพันธ์ได้ กฎผลหารต้องมีตัวส่วนไม่เป็นศูนย์ ln x ต้องมี x > 0 และ aˣ สมมติ a > 0 สำหรับ"
  },
  {
    "url": "derivatives.html#tangent",
    "en": "3. Tangent line visualization $f(x)=x^2$",
    "th": "3. ภาพเส้นสัมผัส",
    "text": "3. Tangent line visualization 3. ภาพเส้นสัมผัส Interactive โต้ตอบได้ $f(x)=x^2$ Choose a function and move the point. Reduce h to compare the secant slope with the tangent slope; the derivative curve records those tangent slopes. เลือกฟังก์ชันแล้วเลื่อนจุด ลด h เพื่อเปรียบเทียบความชันเส้นตัดกับเส้นสัมผัส กราฟอนุพันธ์บันทึกค่าความชันเส้นสัมผัสเหล่านี้ Function ฟังก์ชัน x² x³ − 3x sin(x) $x_0=$ 1.0 Secant interval h ช่วงเส้นตัด h Show derivative curve (dashed) แสดงกราฟอนุพันธ์ (เส้นประ) Slope ความชัน 2.00 Rule กฎ $f'(x)=2x$ Function, tangent, secant and derivative graphs กราฟฟังก์ชัน เส้นสัมผัส เส้นตัด และอนุพันธ์ Tangent line เส้นสัมผัส $$y-f(a)=f'(a)(x-a)$$",
    "previewEn": "Interactive Choose a function and move the point. Reduce h to compare the secant slope with the tangent slope; the derivative curve records those tangent slopes",
    "previewTh": "โต้ตอบได้ เลือกฟังก์ชันแล้วเลื่อนจุด ลด h เพื่อเปรียบเทียบความชันเส้นตัดกับเส้นสัมผัส กราฟอนุพันธ์บันทึกค่าความชันเส้นสัมผัสเหล่านี้ ฟังก์ชัน ช่วงเส้นตัด h แสดง"
  },
  {
    "url": "derivatives.html#applications",
    "en": "4. Applications of derivatives Increasing and decreasing Optimization Motion",
    "th": "4. การประยุกต์อนุพันธ์ ช่วงเพิ่มและช่วงลด การหาค่าสูงสุด/ต่ำสุด การเคลื่อนที่",
    "text": "4. Applications of derivatives 4. การประยุกต์อนุพันธ์ Increasing and decreasing ช่วงเพิ่มและช่วงลด If $f'(x)>0$ throughout an interval, the function is strictly increasing there; if $f'(x)<0$ throughout, it is strictly decreasing. ถ้า $f'(x)>0$ ตลอดช่วง ฟังก์ชันจะเพิ่มอย่างเคร่งครัดในช่วงนั้น และถ้า $f'(x)<0$ ตลอดช่วง ฟังก์ชันจะลดอย่างเคร่งครัด Optimization การหาค่าสูงสุด/ต่ำสุด Find critical points where $f'(x)=0$ or $f'$ is undefined, then classify them using sign changes or the second derivative. หาจุดวิกฤตจาก $f'(x)=0$ หรือจุดที่ $f'$ ไม่มีค่า จากนั้นจำแนกด้วยเครื่องหมายของอนุพันธ์หรืออนุพันธ์อันดับสอง Optimization example ตัวอย่างการหาค่าสุดขั้ว For $f(x)=-x^2+6x+1$, $f'(x)=-2x+6=0$ gives $x=3$. Since $f''(x)=-2<0$, this point is a local maximum. สำหรับ $f(x)=-x^2+6x+1$ จะได้ $f'(x)=-2x+6=0$ ดังนั้น $x=3$ และเพราะ $f''(x)=-2<0$ จุดนี้เป็นค่าสูงสุดเฉพาะที่ Motion การเคลื่อนที่ $$v(t)=s'(t),\\qquad a(t)=v'(t)=s''(t)$$",
    "previewEn": "If $f'(x)>0$ throughout an interval, the function is strictly increasing there; if $f'(x)<0$ throughout, it is strictly decreasing. Find critical points where $",
    "previewTh": "ถ้า $f'(x)>0$ ตลอดช่วง ฟังก์ชันจะเพิ่มอย่างเคร่งครัดในช่วงนั้น และถ้า $f'(x)<0$ ตลอดช่วง ฟังก์ชันจะลดอย่างเคร่งครัด หาจุดวิกฤตจาก $f'(x)=0$ หรือจุดที่ $f'$ ไม่ม"
  },
  {
    "url": "derivatives.html#calculator",
    "en": "5. Derivative calculator",
    "th": "5. เครื่องคำนวณอนุพันธ์",
    "text": "5. Derivative calculator 5. เครื่องคำนวณอนุพันธ์ Symbolic calculator เครื่องคำนวณเชิงสัญลักษณ์ Enter an expression in x, such as x^3*sin(x), exp(2*x), or log(x). ใส่นิพจน์ที่มี x เช่น x^3*sin(x), exp(2*x) หรือ log(x) Expression f(x) นิพจน์ f(x) Differentiate หาอนุพันธ์ Derivative order อันดับอนุพันธ์ 1 2 3 Evaluate at x (optional) หาค่าที่ x (ไม่บังคับ) Use x, + − * / ^, sin, cos, tan, exp, log (or ln), sqrt. Angles are in radians. Up to 240 characters. ใช้ x, + − * / ^, sin, cos, tan, exp, log (หรือ ln), sqrt มุมเป็นเรเดียน ใส่ได้ไม่เกิน 240 ตัวอักษร Result appears here. คำตอบจะแสดงตรงนี้ Original function and derivative ฟังก์ชันเดิมและอนุพันธ์",
    "previewEn": "Symbolic calculator Enter an expression in x, such as x^3*sin(x), exp(2*x), or log(x). Expression f(x) Differentiate Derivative order 1 2 3 Evaluate at x (optio",
    "previewTh": "เครื่องคำนวณเชิงสัญลักษณ์ ใส่นิพจน์ที่มี x เช่น x^3*sin(x), exp(2*x) หรือ log(x) นิพจน์ f(x) หาอนุพันธ์ อันดับอนุพันธ์ หาค่าที่ x (ไม่บังคับ) ใช้ x, + − * / ^, "
  },
  {
    "url": "derivatives.html#implicit",
    "en": "6. Implicit and logarithmic differentiation",
    "th": "6. อนุพันธ์โดยปริยายและลอการิทึม",
    "text": "6. Implicit and logarithmic differentiation 6. อนุพันธ์โดยปริยายและลอการิทึม When x and y are related by an equation, treat y as a function of x. Each derivative involving y needs the chain rule. เมื่อ x และ y สัมพันธ์กันด้วยสมการ ให้มอง y เป็นฟังก์ชันของ x ทุกครั้งที่หาอนุพันธ์พจน์ที่มี y ต้องใช้กฎลูกโซ่ A circle วงกลม $$x^2+y^2=25\\quad\\Longrightarrow\\quad 2x+2y\\frac{dy}{dx}=0\\quad\\Longrightarrow\\quad\\frac{dy}{dx}=-\\frac{x}{y}$$ At (3,4), the slope is −3/4. The formula requires y ≠ 0; at (±5,0) the circle has vertical tangents and cannot locally be a differentiable graph y(x). ที่ (3,4) ความชันเท่ากับ −3/4 สูตรนี้ต้องมี y ≠ 0 ที่ (±5,0) วงกลมมีเส้นสัมผัสแนวตั้ง และไม่สามารถเขียนเป็นกราฟ y(x) ที่หาอนุพันธ์ได้ในบริเวณนั้น For variable bases and exponents, take logarithms before differentiating. The real-valued function xˣ below is considered on x > 0. เมื่อทั้งฐานและเลขชี้กำลังเป็นตัวแปร ให้ใช้ลอการิทึมก่อนหาอนุพันธ์ ฟังก์ชันค่าจริง xˣ ด้านล่างพิจารณาบนโดเมน x > 0 $$y=x^x\\;\\Rightarrow\\;\\ln y=x\\ln x\\;\\Rightarrow\\;\\frac{y^{\\prime}}y=\\ln x+1\\;\\Rightarrow\\;y^{\\prime}=x^x(\\ln x+1)$$",
    "previewEn": "When x and y are related by an equation, treat y as a function of x. Each derivative involving y needs the chain rule. A circle $$x^2+y^2=25\\quad\\Longrightarrow",
    "previewTh": "เมื่อ x และ y สัมพันธ์กันด้วยสมการ ให้มอง y เป็นฟังก์ชันของ x ทุกครั้งที่หาอนุพันธ์พจน์ที่มี y ต้องใช้กฎลูกโซ่ วงกลม ที่ (3,4) ความชันเท่ากับ −3/4 สูตรนี้ต้องมี"
  },
  {
    "url": "derivatives.html#mean-value",
    "en": "7. Mean Value Theorem",
    "th": "7. ทฤษฎีบทค่ากลาง",
    "text": "7. Mean Value Theorem 7. ทฤษฎีบทค่ากลาง Mean Value Theorem ทฤษฎีบทค่ากลาง If f is continuous on [a,b] and differentiable on (a,b), with a < b, there is a point c inside the interval whose tangent slope equals the average rate over the whole interval. ถ้า f ต่อเนื่องบน [a,b] และหาอนุพันธ์ได้บน (a,b) โดย a < b จะมีจุด c ภายในช่วงที่ความชันเส้นสัมผัสเท่ากับอัตราการเปลี่ยนแปลงเฉลี่ยตลอดช่วง $$f^{\\prime}(c)=\\frac{f(b)-f(a)}{b-a},\\qquad c\\in(a,b)$$ Rolle’s theorem is the special case f(a) = f(b), giving f′(c) = 0. The hypotheses matter: |x| on [−1,1] has equal endpoint values but no horizontal tangent because it is not differentiable at zero. ทฤษฎีบทของโรลล์เป็นกรณีพิเศษเมื่อ f(a) = f(b) จึงได้ f′(c) = 0 เงื่อนไขมีความสำคัญ เช่น |x| บน [−1,1] มีค่าที่ปลายเท่ากันแต่ไม่มีเส้นสัมผัสแนวนอน เพราะหาอนุพันธ์ที่ศูนย์ไม่ได้ Find the guaranteed point หาจุดที่ทฤษฎีบทรองรับ For f(x) = x² on [1,3], the secant slope is (9−1)/(3−1) = 4. Solve 2c = 4 to obtain c = 2, which lies in (1,3). สำหรับ f(x) = x² บน [1,3] ความชันเส้นตัดเท่ากับ (9−1)/(3−1) = 4 แก้ 2c = 4 ได้ c = 2 ซึ่งอยู่ใน (1,3)",
    "previewEn": "Mean Value Theorem If f is continuous on [a,b] and differentiable on (a,b), with a < b, there is a point c inside the interval whose tangent slope equals the av",
    "previewTh": "ทฤษฎีบทค่ากลาง ถ้า f ต่อเนื่องบน [a,b] และหาอนุพันธ์ได้บน (a,b) โดย a < b จะมีจุด c ภายในช่วงที่ความชันเส้นสัมผัสเท่ากับอัตราการเปลี่ยนแปลงเฉลี่ยตลอดช่วง ทฤษฎีบ"
  },
  {
    "url": "derivatives.html#curve-analysis",
    "en": "8. Curve analysis and global extrema",
    "th": "8. วิเคราะห์กราฟและค่าสุดขั้วสัมบูรณ์",
    "text": "8. Curve analysis and global extrema 8. วิเคราะห์กราฟและค่าสุดขั้วสัมบูรณ์ A critical number is an interior point in the domain where f′ is zero or does not exist. On a closed bounded interval, a continuous function attains its absolute maximum and minimum. Compare all critical values and both endpoint values. จำนวนวิกฤตคือจุดภายในโดเมนที่ f′ เป็นศูนย์หรือไม่มีค่า ฟังก์ชันต่อเนื่องบนช่วงปิดที่มีขอบเขตจะมีค่าสูงสุดและต่ำสุดสัมบูรณ์ ให้เปรียบเทียบค่าที่จุดวิกฤตทั้งหมดและปลายช่วงทั้งสอง $$f(x)=x^3-3x,\\quad f^{\\prime}(x)=3(x-1)(x+1),\\quad f^{\\prime^{\\prime}}(x)=6x$$ On [−2,2], test x = −2, −1, 1, 2. The corresponding values are −2, 2, −2, 2. The maximum is 2 and the minimum is −2; both can occur at multiple points. The curve is concave down for x < 0 and concave up for x > 0, so (0,0) is an inflection point. บน [−2,2] ตรวจ x = −2, −1, 1, 2 ได้ค่าฟังก์ชัน −2, 2, −2, 2 ตามลำดับ ค่าสูงสุดคือ 2 และต่ำสุดคือ −2 ซึ่งอาจเกิดที่หลายจุด กราฟเว้าลงเมื่อ x < 0 และเว้าขึ้นเมื่อ x > 0 ดังนั้น (0,0) เป็นจุดเปลี่ยนเว้า Common mistake ข้อผิดพลาดที่พบบ่อย The equation f″(c) = 0 only identifies a candidate inflection point; concavity must change. For x⁴, f″(0) = 0 but there is no inflection. Likewise, f″(c) = 0 makes the second derivative test inconclusive. สมการ f″(c) = 0 ให้เพียงจุดที่อาจเปลี่ยนเว้า ต้องตรวจว่าความเว้าเปลี่ยนจริง สำหรับ x⁴ มี f″(0) = 0 แต่ไม่เปลี่ยนเว้า และถ้า f″(c) = 0 การทดสอบอนุพันธ์อันดับสองยังสรุปไม่ได้",
    "previewEn": "A critical number is an interior point in the domain where f′ is zero or does not exist. On a closed bounded interval, a continuous function attains its absolut",
    "previewTh": "จำนวนวิกฤตคือจุดภายในโดเมนที่ f′ เป็นศูนย์หรือไม่มีค่า ฟังก์ชันต่อเนื่องบนช่วงปิดที่มีขอบเขตจะมีค่าสูงสุดและต่ำสุดสัมบูรณ์ ให้เปรียบเทียบค่าที่จุดวิกฤตทั้งหมดแล"
  },
  {
    "url": "derivatives.html#related-rates",
    "en": "9. Related rates and linear approximation",
    "th": "9. อัตราสัมพัทธ์และการประมาณเชิงเส้น",
    "text": "9. Related rates and linear approximation 9. อัตราสัมพัทธ์และการประมาณเชิงเส้น An expanding sphere ทรงกลมที่กำลังขยาย A sphere’s radius grows at 2 cm/s. Differentiate V = 4πr³/3 with respect to time before substituting r = 3 cm. รัศมีทรงกลมเพิ่มด้วยอัตรา 2 ซม./วินาที หาอนุพันธ์ V = 4πr³/3 เทียบกับเวลาก่อนแทน r = 3 ซม. $$\\frac{dV}{dt}=4\\pi r^2\\frac{dr}{dt}=4\\pi(3)^2(2)=72\\pi\\;\\mathrm{cm^3/s}$$ A tangent line also provides a local approximation. For differentiable f near a, L(x) = f(a) + f′(a)(x−a). It is accurate near a, but is not an exact equality in general. เส้นสัมผัสใช้ประมาณค่าใกล้จุดได้ด้วย ถ้า f หาอนุพันธ์ได้ใกล้ a ให้ L(x) = f(a) + f′(a)(x−a) การประมาณแม่นยำใกล้ a แต่โดยทั่วไปไม่ใช่สมการที่เท่ากันพอดี $$\\sqrt{4.1}\\approx \\sqrt4+\\frac{1}{2\\sqrt4}(4.1-4)=2.025$$ For Newton’s method, the tangent’s x-intercept becomes the next guess: xₙ₊₁ = xₙ − f(xₙ)/f′(xₙ). A zero derivative, a poor starting guess, or a discontinuity can prevent convergence. สำหรับวิธีนิวตัน ใช้จุดตัดแกน x ของเส้นสัมผัสเป็นค่าประมาณถัดไป: xₙ₊₁ = xₙ − f(xₙ)/f′(xₙ) หากอนุพันธ์เป็นศูนย์ ค่าเริ่มต้นไม่เหมาะสม หรือมีจุดไม่ต่อเนื่อง อาจไม่ลู่เข้า",
    "previewEn": "An expanding sphere A sphere’s radius grows at 2 cm/s. Differentiate V = 4πr³/3 with respect to time before substituting r = 3 cm. $$\\frac{dV}{dt}=4\\pi r^2\\frac",
    "previewTh": "ทรงกลมที่กำลังขยาย รัศมีทรงกลมเพิ่มด้วยอัตรา 2 ซม./วินาที หาอนุพันธ์ V = 4πr³/3 เทียบกับเวลาก่อนแทน r = 3 ซม. เส้นสัมผัสใช้ประมาณค่าใกล้จุดได้ด้วย ถ้า f หาอนุพั"
  },
  {
    "url": "integrals.html#riemann",
    "en": "1. Riemann sums and area $f(x)=x^2+1$ on $[0,2]$",
    "th": "1. ผลบวกรีมันน์และพื้นที่ $f(x)=x^2+1$ บน $[0,2]$",
    "text": "1. Riemann sums and area 1. ผลบวกรีมันน์และพื้นที่ $$\\int_a^b f(x)\\,dx=\\lim_{n\\to\\infty}\\sum_{i=1}^{n}f(x_i^*)\\,\\Delta x$$ A definite integral is the limit of finer and finer rectangle sums. ปริพันธ์จำกัดเขตคือขีดจำกัดของผลรวมพื้นที่สี่เหลี่ยมที่แบ่งช่วงให้ละเอียดขึ้นเรื่อย ๆ For continuous f on [a,b], equal subintervals have width Δx = (b−a)/n, and xᵢ* can be any sample in subinterval i. The limit is independent of those choices. เมื่อ f ต่อเนื่องบน [a,b] ช่วงย่อยเท่ากันมีความกว้าง Δx = (b−a)/n และ xᵢ* เป็นจุดตัวอย่างใดก็ได้ในช่วงย่อยที่ i ลิมิตไม่ขึ้นกับการเลือกจุดเหล่านี้ Riemann rectangle sum ผลบวกพื้นที่สี่เหลี่ยมรีมันน์ Interactive โต้ตอบได้ $f(x)=x^2+1$ on $[0,2]$ $f(x)=x^2+1$ บน $[0,2]$ Choose left, midpoint or right samples. Increase the number of rectangles to approach the exact integral 14/3. Compare the absolute errors. เลือกจุดซ้าย กึ่งกลาง หรือขวา เพิ่มจำนวนสี่เหลี่ยมเพื่อเข้าใกล้ปริพันธ์จริง 14/3 แล้วเปรียบเทียบความคลาดเคลื่อนสัมบูรณ์ n = 6 Sampling rule วิธีเลือกจุด Left endpoints Midpoints Right endpoints Approx. ค่าประมาณ — Exact ค่าจริง 4.6667",
    "previewEn": "$$\\int_a^b f(x)\\,dx=\\lim_{n\\to\\infty}\\sum_{i=1}^{n}f(x_i^*)\\,\\Delta x$$ A definite integral is the limit of finer and finer rectangle sums. For continuous f on ",
    "previewTh": "ปริพันธ์จำกัดเขตคือขีดจำกัดของผลรวมพื้นที่สี่เหลี่ยมที่แบ่งช่วงให้ละเอียดขึ้นเรื่อย ๆ เมื่อ f ต่อเนื่องบน [a,b] ช่วงย่อยเท่ากันมีความกว้าง Δx = (b−a)/n และ xᵢ* "
  },
  {
    "url": "integrals.html#antiderivative",
    "en": "2. Antiderivatives",
    "th": "2. ปฏิยานุพันธ์",
    "text": "2. Antiderivatives 2. ปฏิยานุพันธ์ An antiderivative of $f$ is a function $F$ such that $F'=f$. ปฏิยานุพันธ์ของ $f$ คือฟังก์ชัน $F$ ที่ทำให้ $F'=f$ $$\\int f(x)\\,dx=F(x)+C$$ Power rule กฎยกกำลัง $$\\int x^n dx=\\frac{x^{n+1}}{n+1}+C,\\quad n\\ne-1$$ Logarithm ลอการิทึม $$\\int\\frac1x\\,dx=\\ln|x|+C$$ $$\\int e^x dx=e^x+C$$ $$\\int\\sin x\\,dx=-\\cos x+C$$ The constant $C$ matters because every vertical shift of an antiderivative has the same derivative. ค่าคงที่ $C$ สำคัญ เพราะฟังก์ชันที่ต่างกันด้วยการเลื่อนแนวตั้งมีอนุพันธ์เหมือนกัน",
    "previewEn": "An antiderivative of $f$ is a function $F$ such that $F'=f$. $$\\int f(x)\\,dx=F(x)+C$$ Power rule $$\\int x^n dx=\\frac{x^{n+1}}{n+1}+C,\\quad n\\ne-1$$ Logarithm $$",
    "previewTh": "ปฏิยานุพันธ์ของ $f$ คือฟังก์ชัน $F$ ที่ทำให้ $F'=f$ กฎยกกำลัง ลอการิทึม ค่าคงที่ $C$ สำคัญ เพราะฟังก์ชันที่ต่างกันด้วยการเลื่อนแนวตั้งมีอนุพันธ์เหมือนกัน"
  },
  {
    "url": "integrals.html#ftc",
    "en": "3. Fundamental Theorem of Calculus",
    "th": "3. ทฤษฎีบทมูลฐานของแคลคูลัส",
    "text": "Assume f is continuous on [a,b]; in Part I take x in the interior. In Part II, F is an antiderivative on that interval. สมมติ f ต่อเนื่องบน [a,b] ในส่วนที่ 1 ให้ x อยู่ภายในช่วง และในส่วนที่ 2 ให้ F เป็นปฏิยานุพันธ์บนช่วงนั้น 3. Fundamental Theorem of Calculus 3. ทฤษฎีบทมูลฐานของแคลคูลัส FTC I ทฤษฎีบทมูลฐาน ส่วนที่ 1 $$\\frac{d}{dx}\\int_a^x f(t)\\,dt=f(x)$$ FTC II ทฤษฎีบทมูลฐาน ส่วนที่ 2 $$\\int_a^b f(x)\\,dx=F(b)-F(a)\\quad\\quad F'=f$$ This theorem says differentiation and integration are inverse processes in a precise sense. ทฤษฎีบทนี้บอกว่า “การหาอนุพันธ์” และ “การอินทิเกรต” เป็นกระบวนการผกผันกันในความหมายที่ชัดเจน Example ตัวอย่าง $$\\int_0^2(x^2+1)dx=\\left[\\frac{x^3}{3}+x\\right]_0^2=\\frac83+2=\\frac{14}{3}$$",
    "previewEn": "Assume f is continuous on [a,b]; in Part I take x in the interior. In Part II, F is an antiderivative on that interval. FTC I $$\\frac{d}{dx}\\int_a^x f(t)\\,dt=f(",
    "previewTh": "สมมติ f ต่อเนื่องบน [a,b] ในส่วนที่ 1 ให้ x อยู่ภายในช่วง และในส่วนที่ 2 ให้ F เป็นปฏิยานุพันธ์บนช่วงนั้น ทฤษฎีบทมูลฐาน ส่วนที่ 1 ทฤษฎีบทมูลฐาน ส่วนที่ 2 ทฤษฎีบ"
  },
  {
    "url": "integrals.html#techniques",
    "en": "4. Integration techniques Substitution Integration by parts",
    "th": "4. เทคนิคการอินทิเกรต การแทนค่า อินทิเกรตโดยส่วน",
    "text": "4. Integration techniques 4. เทคนิคการอินทิเกรต Substitution การแทนค่า $$\\int f(g(x))g'(x)\\,dx=\\int f(u)\\,du$$ $$\\int 2x\\cos(x^2)dx$$ Let $u=x^2$, so $du=2x\\,dx$. Then the integral becomes $\\int\\cos u\\,du=\\sin u+C=\\sin(x^2)+C$. ให้ $u=x^2$ จะได้ $du=2x\\,dx$ จึงเหลือ $\\int\\cos u\\,du=\\sin u+C=\\sin(x^2)+C$ Integration by parts อินทิเกรตโดยส่วน $$\\int u\\,dv=uv-\\int v\\,du$$ $$\\int xe^x dx=xe^x-\\int e^x dx=xe^x-e^x+C$$",
    "previewEn": "$$\\int f(g(x))g'(x)\\,dx=\\int f(u)\\,du$$ $$\\int 2x\\cos(x^2)dx$$ Let $u=x^2$, so $du=2x\\,dx$. Then the integral becomes $\\int\\cos u\\,du=\\sin u+C=\\sin(x^2)+C$. $$\\",
    "previewTh": "ให้ $u=x^2$ จะได้ $du=2x\\,dx$ จึงเหลือ $\\int\\cos u\\,du=\\sin u+C=\\sin(x^2)+C$"
  },
  {
    "url": "integrals.html#calculator",
    "en": "5. Integral calculator",
    "th": "5. เครื่องคำนวณปริพันธ์",
    "text": "5. Integral calculator 5. เครื่องคำนวณปริพันธ์ Symbolic + definite เชิงสัญลักษณ์และจำกัดเขต Enter a function and optional bounds. The calculator shows a symbolic antiderivative when available and a numerical definite integral. ใส่ฟังก์ชันและขอบเขต เครื่องคำนวณจะแสดงปริพันธ์ไม่จำกัดเขตเชิงสัญลักษณ์เมื่อทำได้ และคำนวณปริพันธ์จำกัดเขตเชิงตัวเลข Integrand f(x) ฟังก์ชันใต้ปริพันธ์ f(x) Integrate อินทิเกรต Lower bound a (optional) ขอบล่าง a (ไม่บังคับ) Upper bound b (optional) ขอบบน b (ไม่บังคับ) Leave both bounds blank for an antiderivative. Use finite decimal bounds for numerical integration of a continuous real function. Reversed bounds are supported. Estimates cannot certify convergence or detect every singularity. Angles are in radians. เว้นขอบทั้งสองว่างเพื่อหาปฏิยานุพันธ์ ใช้ขอบเป็นเลขทศนิยมจำกัดสำหรับปริพันธ์เชิงตัวเลขของฟังก์ชันค่าจริงที่ต่อเนื่อง สลับขอบได้ ค่าประมาณไม่สามารถยืนยันการลู่เข้าหรือตรวจพบจุดเอกฐานทุกจุด มุมเป็นเรเดียน Result appears here. คำตอบจะแสดงตรงนี้ Function and signed integral region ฟังก์ชันและพื้นที่ปริพันธ์แบบมีเครื่องหมาย",
    "previewEn": "Symbolic + definite Enter a function and optional bounds. The calculator shows a symbolic antiderivative when available and a numerical definite integral. Integ",
    "previewTh": "เชิงสัญลักษณ์และจำกัดเขต ใส่ฟังก์ชันและขอบเขต เครื่องคำนวณจะแสดงปริพันธ์ไม่จำกัดเขตเชิงสัญลักษณ์เมื่อทำได้ และคำนวณปริพันธ์จำกัดเขตเชิงตัวเลข ฟังก์ชันใต้ปริพันธ"
  },
  {
    "url": "integrals.html#signed-area",
    "en": "6. Signed accumulation and geometric area",
    "th": "6. การสะสมแบบมีเครื่องหมายและพื้นที่เรขาคณิต",
    "text": "6. Signed accumulation and geometric area 6. การสะสมแบบมีเครื่องหมายและพื้นที่เรขาคณิต A definite integral counts values below the x-axis negatively. Geometric area is nonnegative and uses |f|. Split the interval at zeros where the sign changes; do not take the absolute value of the final signed integral. ปริพันธ์จำกัดเขตนับค่าที่อยู่ใต้แกน x เป็นลบ พื้นที่เรขาคณิตไม่ติดลบและใช้ |f| ให้แบ่งช่วงที่รากซึ่งฟังก์ชันเปลี่ยนเครื่องหมาย ไม่ใช่ใส่ค่าสัมบูรณ์ให้ปริพันธ์สุดท้าย $$\\int_{-1}^{1}x\\,dx=0,\\qquad \\int_{-1}^{1}|x|\\,dx=1$$ For two curves with upper curve g and lower curve f on [a,b], integrate g−f. If the curves cross, split at each intersection and determine which is above on each subinterval. สำหรับสองเส้นโค้งที่ g อยู่บนและ f อยู่ล่างบน [a,b] ให้หาปริพันธ์ g−f ถ้าเส้นโค้งตัดกันให้แบ่งที่จุดตัดแล้วพิจารณาเส้นบนในแต่ละช่วง $$A=\\int_0^1(x-x^2)\\,dx=\\left[\\frac{x^2}{2}-\\frac{x^3}{3}\\right]_0^1=\\frac16$$ Upper bound b for f(x) = x on [−1,b] ขอบบน b ของ f(x) = x บน [−1,b] Signed area and geometric area พื้นที่แบบมีเครื่องหมายและพื้นที่เรขาคณิต",
    "previewEn": "A definite integral counts values below the x-axis negatively. Geometric area is nonnegative and uses |f|. Split the interval at zeros where the sign changes; d",
    "previewTh": "ปริพันธ์จำกัดเขตนับค่าที่อยู่ใต้แกน x เป็นลบ พื้นที่เรขาคณิตไม่ติดลบและใช้ |f| ให้แบ่งช่วงที่รากซึ่งฟังก์ชันเปลี่ยนเครื่องหมาย ไม่ใช่ใส่ค่าสัมบูรณ์ให้ปริพันธ์สุ"
  },
  {
    "url": "integrals.html#ftc-conditions",
    "en": "7. The FTC: hypotheses and variable bounds",
    "th": "7. เงื่อนไขของทฤษฎีบทมูลฐานและขอบเขตตัวแปร",
    "text": "7. The FTC: hypotheses and variable bounds 7. เงื่อนไขของทฤษฎีบทมูลฐานและขอบเขตตัวแปร For the introductory FTC, assume f is continuous on [a,b]. Then A(x) = ∫ₐˣ f(t)dt is differentiable for interior x and A′(x) = f(x). If F is any antiderivative of f on the interval, ∫ₐᵇ f = F(b)−F(a). Continuity is a sufficient hypothesis; applying the formula across a singularity is invalid. สำหรับทฤษฎีบทมูลฐานระดับต้น สมมติ f ต่อเนื่องบน [a,b] แล้ว A(x) = ∫ₐˣ f(t)dt หาอนุพันธ์ได้ที่จุดภายในและ A′(x) = f(x) ถ้า F เป็นปฏิยานุพันธ์ของ f ในช่วงนั้น จะได้ ∫ₐᵇ f = F(b)−F(a) ความต่อเนื่องเป็นเงื่อนไขที่เพียงพอ และห้ามใช้สูตรข้ามจุดเอกฐานโดยไม่ตรวจสอบ $$\\frac{d}{dx}\\int_{u(x)}^{v(x)}f(t)\\,dt=f(v(x))v^{\\prime}(x)-f(u(x))u^{\\prime}(x)$$ Use the chain rule at each bound ใช้กฎลูกโซ่ที่ขอบแต่ละด้าน $$\\frac{d}{dx}\\int_x^{x^2}\\cos t\\,dt=2x\\cos(x^2)-\\cos x$$ Reversing the bounds reverses the sign; an interval of zero length has integral zero. These algebraic properties refer to oriented accumulation, not geometric area. เมื่อสลับขอบเขต เครื่องหมายจะเปลี่ยน และช่วงที่ยาวศูนย์มีปริพันธ์เป็นศูนย์ สมบัติเหล่านี้ใช้กับการสะสมที่มีทิศทาง ไม่ใช่พื้นที่เรขาคณิต",
    "previewEn": "For the introductory FTC, assume f is continuous on [a,b]. Then A(x) = ∫ₐˣ f(t)dt is differentiable for interior x and A′(x) = f(x). If F is any antiderivative ",
    "previewTh": "สำหรับทฤษฎีบทมูลฐานระดับต้น สมมติ f ต่อเนื่องบน [a,b] แล้ว A(x) = ∫ₐˣ f(t)dt หาอนุพันธ์ได้ที่จุดภายในและ A′(x) = f(x) ถ้า F เป็นปฏิยานุพันธ์ของ f ในช่วงนั้น จะไ"
  },
  {
    "url": "integrals.html#more-techniques",
    "en": "8. Choosing an integration technique",
    "th": "8. เลือกเทคนิคการอินทิเกรต",
    "text": "8. Choosing an integration technique 8. เลือกเทคนิคการอินทิเกรต First simplify algebra and look for a known derivative. Use substitution for a composition with its inner derivative, parts for a product that becomes simpler when differentiated, and partial fractions for rational functions after polynomial division if needed. เริ่มจากจัดรูปพีชคณิตและมองหาอนุพันธ์ที่รู้จัก ใช้การแทนค่าสำหรับฟังก์ชันประกอบที่มีอนุพันธ์ชั้นใน ใช้โดยส่วนเมื่อผลคูณง่ายขึ้นหลังหาอนุพันธ์ และใช้เศษส่วนย่อยสำหรับฟังก์ชันตรรกยะ โดยหารพหุนามก่อนถ้าจำเป็น Definite substitution: change the bounds แทนค่าในปริพันธ์จำกัดเขต: เปลี่ยนขอบเขต $$\\int_0^1 2x\\cos(x^2)\\,dx=\\int_0^1\\cos u\\,du=\\sin1$$ Here u = x² and du = 2x dx; x = 0 gives u = 0 and x = 1 gives u = 1. Once the bounds are in u, finish in u. ในที่นี้ u = x² และ du = 2x dx เมื่อ x = 0 ได้ u = 0 และเมื่อ x = 1 ได้ u = 1 เมื่อเปลี่ยนขอบเป็น u แล้ว ให้คำนวณจนจบในตัวแปร u Partial fractions เศษส่วนย่อย $$\\frac1{x^2-1}=\\frac12\\left(\\frac1{x-1}-\\frac1{x+1}\\right)$$ $$\\int\\frac{dx}{x^2-1}=\\frac12\\ln|x-1|-\\frac12\\ln|x+1|+C$$ The formula holds separately on intervals avoiding x = ±1. Absolute values extend the real logarithms to all nonzero arguments. สูตรใช้แยกกันบนช่วงที่ไม่ผ่าน x = ±1 ค่าสัมบูรณ์ทำให้ลอการิทึมค่าจริงใช้ได้เมื่ออาร์กิวเมนต์เดิมไม่เป็นศูนย์ Trigonometric identities เอกลักษณ์ตรีโกณมิติ $$\\int\\sin^2x\\,dx=\\int\\frac{1-\\cos2x}{2}\\,dx=\\frac{x}{2}-\\frac{\\sin2x}{4}+C$$",
    "previewEn": "First simplify algebra and look for a known derivative. Use substitution for a composition with its inner derivative, parts for a product that becomes simpler w",
    "previewTh": "เริ่มจากจัดรูปพีชคณิตและมองหาอนุพันธ์ที่รู้จัก ใช้การแทนค่าสำหรับฟังก์ชันประกอบที่มีอนุพันธ์ชั้นใน ใช้โดยส่วนเมื่อผลคูณง่ายขึ้นหลังหาอนุพันธ์ และใช้เศษส่วนย่อยส"
  },
  {
    "url": "integrals.html#improper",
    "en": "9. Improper integrals and convergence",
    "th": "9. ปริพันธ์ไม่ตรงแบบและการลู่เข้า",
    "text": "9. Improper integrals and convergence 9. ปริพันธ์ไม่ตรงแบบและการลู่เข้า An infinite interval or an unbounded integrand requires a limit. Evaluate the proper integral first, then take that limit. At an interior singularity, both sides must converge separately. ช่วงอนันต์หรือฟังก์ชันที่ไม่มีขอบเขตต้องใช้นิยามผ่านลิมิต คำนวณปริพันธ์บนช่วงปกติก่อนแล้วจึงหาลิมิต ถ้ามีจุดเอกฐานภายในช่วง ทั้งสองด้านต้องลู่เข้าแยกกัน $$\\int_1^{\\infty}\\frac{dx}{x^p}=\\lim_{R\\to\\infty}\\int_1^R x^{-p}\\,dx=\\frac1{p-1}\\quad(p>1)$$ For p ≤ 1 this tail integral diverges. Near zero, ∫₀¹ x⁻ᵖ dx instead converges precisely when p < 1. The harmonic case p = 1 gives a logarithm in both settings. เมื่อ p ≤ 1 ปริพันธ์ปลายอนันต์นี้ลู่ออก ส่วนบริเวณใกล้ศูนย์ ∫₀¹ x⁻ᵖ dx จะลู่เข้าก็ต่อเมื่อ p < 1 กรณี p = 1 ให้ลอการิทึมทั้งสองแบบ Cancellation is not convergence การหักล้างไม่ใช่การลู่เข้า The improper integral of 1/x from −1 to 1 diverges: its left and right integrals diverge separately. A symmetric cancellation of zero is a Cauchy principal value, not the improper integral. The calculator is intended for continuous functions on finite intervals. ปริพันธ์ไม่ตรงแบบของ 1/x จาก −1 ถึง 1 ลู่ออก เพราะปริพันธ์ด้านซ้ายและขวาลู่ออกแยกกัน การหักล้างแบบสมมาตรที่ได้ศูนย์เป็นค่าหลักโคชี ไม่ใช่ค่าปริพันธ์ไม่ตรงแบบ เครื่องคำนวณนี้ใช้กับฟังก์ชันต่อเนื่องบนช่วงจำกัด",
    "previewEn": "An infinite interval or an unbounded integrand requires a limit. Evaluate the proper integral first, then take that limit. At an interior singularity, both side",
    "previewTh": "ช่วงอนันต์หรือฟังก์ชันที่ไม่มีขอบเขตต้องใช้นิยามผ่านลิมิต คำนวณปริพันธ์บนช่วงปกติก่อนแล้วจึงหาลิมิต ถ้ามีจุดเอกฐานภายในช่วง ทั้งสองด้านต้องลู่เข้าแยกกัน เมื่อ p"
  },
  {
    "url": "integrals.html#numerical",
    "en": "10. Numerical integration and error",
    "th": "10. การอินทิเกรตเชิงตัวเลขและความคลาดเคลื่อน",
    "text": "10. Numerical integration and error 10. การอินทิเกรตเชิงตัวเลขและความคลาดเคลื่อน $$M_n=\\Delta x\\sum_{i=1}^n f\\!\\left(a+\\left(i-\\frac12\\right)\\Delta x\\right),\\qquad\\Delta x=\\frac{b-a}{n}$$ Left and right sums use the corresponding endpoint of each subinterval. For increasing functions, the left sum underestimates and the right sum overestimates the signed integral when a < b. Midpoint and trapezoid rules generally converge faster for smooth functions. ผลบวกซ้ายและขวาใช้ค่าที่ปลายด้านนั้นของแต่ละช่วงย่อย สำหรับฟังก์ชันเพิ่ม เมื่อ a < b ผลบวกซ้ายให้ค่าต่ำและผลบวกขวาให้ค่าสูงกว่าปริพันธ์แบบมีเครื่องหมาย โดยทั่วไปกฎจุดกึ่งกลางและคางหมูลู่เข้าเร็วกว่าเมื่อฟังก์ชันเรียบ Assuming |f″(x)| ≤ K throughout [a,b], เมื่อ |f″(x)| ≤ K ตลอดช่วง [a,b] $$|E_M|\\le\\frac{K(b-a)^3}{24n^2}$$ Simpson’s rule combines quadratic approximations. Adaptive integration subdivides where the estimate changes most. An estimated error is not a proof of continuity or convergence; narrow spikes and singularities require mathematical analysis. กฎซิมป์สันรวมการประมาณด้วยพาราโบลา วิธีปรับช่วงอัตโนมัติแบ่งย่อยบริเวณที่ค่าประมาณเปลี่ยนมาก ค่าคลาดเคลื่อนโดยประมาณไม่ใช่การพิสูจน์ความต่อเนื่องหรือการลู่เข้า ยอดแคบและจุดเอกฐานยังต้องวิเคราะห์ทางคณิตศาสตร์",
    "previewEn": "$$M_n=\\Delta x\\sum_{i=1}^n f\\!\\left(a+\\left(i-\\frac12\\right)\\Delta x\\right),\\qquad\\Delta x=\\frac{b-a}{n}$$ Left and right sums use the corresponding endpoint of",
    "previewTh": "ผลบวกซ้ายและขวาใช้ค่าที่ปลายด้านนั้นของแต่ละช่วงย่อย สำหรับฟังก์ชันเพิ่ม เมื่อ a < b ผลบวกซ้ายให้ค่าต่ำและผลบวกขวาให้ค่าสูงกว่าปริพันธ์แบบมีเครื่องหมาย โดยทั่วไ"
  },
  {
    "url": "practice.html#limits-practice",
    "en": "Limits",
    "th": "ลิมิต",
    "text": "Limits ลิมิต",
    "previewEn": "",
    "previewTh": ""
  },
  {
    "url": "practice.html#limits-1",
    "en": "Limits practice 1",
    "th": "ลิมิต 1",
    "text": "Limit · Easy ลิมิต · พื้นฐาน $$\\lim_{x\\to4}\\frac{x^2-16}{x-4}$$ Step-by-step solution เฉลยทีละขั้นตอน Factor the numerator: แยกตัวประกอบ: $$\\frac{(x-4)(x+4)}{x-4}=x+4$$ $$\\therefore\\;\\lim_{x\\to4}\\frac{x^2-16}{x-4}=8$$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Limit · Easy $$\\lim_{x\\to4}\\frac{x^2-16}{x-4}$$ Step-by-step solution Factor the numerator: $$\\frac{(x-4)(x+4)}{x-4}=x+4$$ $$\\therefore\\;\\lim_{x\\to4}\\frac{x^2-1",
    "previewTh": "ลิมิต · พื้นฐาน เฉลยทีละขั้นตอน แยกตัวประกอบ: ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#limits-2",
    "en": "Limits practice 2",
    "th": "ลิมิต 2",
    "text": "Limit · Medium ลิมิต · ประยุกต์ $$\\lim_{x\\to0}\\frac{\\sqrt{1+3x}-1}{x}$$ Step-by-step solution เฉลยทีละขั้นตอน Multiply by the conjugate. คูณด้วยพจน์สังยุค $$\\frac{\\sqrt{1+3x}-1}{x}\\cdot\\frac{\\sqrt{1+3x}+1}{\\sqrt{1+3x}+1}=\\frac{3}{\\sqrt{1+3x}+1}\\to\\frac32$$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Limit · Medium $$\\lim_{x\\to0}\\frac{\\sqrt{1+3x}-1}{x}$$ Step-by-step solution Multiply by the conjugate. $$\\frac{\\sqrt{1+3x}-1}{x}\\cdot\\frac{\\sqrt{1+3x}+1}{\\sqrt",
    "previewTh": "ลิมิต · ประยุกต์ เฉลยทีละขั้นตอน คูณด้วยพจน์สังยุค ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#limits-3",
    "en": "Limits practice 3",
    "th": "ลิมิต 3",
    "text": "Limit · Concept ลิมิต · แนวคิด If $\\lim_{x\\to2^-}f(x)=5$ and $\\lim_{x\\to2^+}f(x)=7$, what is $\\lim_{x\\to2}f(x)$? ถ้า $\\lim_{x\\to2^-}f(x)=5$ และ $\\lim_{x\\to2^+}f(x)=7$ แล้ว $\\lim_{x\\to2}f(x)$ มีค่าเท่าใด? Step-by-step solution เฉลยทีละขั้นตอน It does not exist because the one-sided limits are different. ไม่มีลิมิตสองด้าน เพราะลิมิตซ้ายและขวามีค่าไม่เท่ากัน Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Limit · Concept If $\\lim_{x\\to2^-}f(x)=5$ and $\\lim_{x\\to2^+}f(x)=7$, what is $\\lim_{x\\to2}f(x)$? Step-by-step solution It does not exist because the one-sided ",
    "previewTh": "ลิมิต · แนวคิด ถ้า $\\lim_{x\\to2^-}f(x)=5$ และ $\\lim_{x\\to2^+}f(x)=7$ แล้ว $\\lim_{x\\to2}f(x)$ มีค่าเท่าใด? เฉลยทีละขั้นตอน ไม่มีลิมิตสองด้าน เพราะลิมิตซ้ายและขวา"
  },
  {
    "url": "practice.html#limits-4",
    "en": "04. Polynomial substitution",
    "th": "แทนค่าในพหุนาม",
    "text": "Foundation พื้นฐาน 04. Polynomial substitution แทนค่าในพหุนาม $$\\lim_{x\\to2}(x^3-2x+1)$$ Step-by-step solution เฉลยทีละขั้นตอน A polynomial is continuous everywhere, so direct substitution is valid. พหุนามต่อเนื่องทุกจุด จึงแทนค่าตรง ๆ ได้ Substitute $x=2$: $2^3-2(2)+1$. แทน $x=2$: $2^3-2(2)+1$ Simplify: 8 − 4 + 1 = 5. จัดรูป: 8 − 4 + 1 = 5 Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Foundation $$\\lim_{x\\to2}(x^3-2x+1)$$ Step-by-step solution A polynomial is continuous everywhere, so direct substitution is valid. Substitute $x=2$: $2^3-2(2)+",
    "previewTh": "พื้นฐาน เฉลยทีละขั้นตอน พหุนามต่อเนื่องทุกจุด จึงแทนค่าตรง ๆ ได้ แทน $x=2$: $2^3-2(2)+1$ จัดรูป: 8 − 4 + 1 = 5 ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#limits-5",
    "en": "05. Scaled sine",
    "th": "ลิมิต sine ที่ปรับสเกล",
    "text": "Foundation พื้นฐาน 05. Scaled sine ลิมิต sine ที่ปรับสเกล $$\\lim_{x\\to0}\\frac{\\sin5x}{2x}$$ Step-by-step solution เฉลยทีละขั้นตอน Rewrite as $\\frac52\\frac{\\sin5x}{5x}$. เขียนเป็น $\\frac52\\frac{\\sin5x}{5x}$ Let u = 5x. Then u tends to zero and sin(u)/u tends to 1 in radians. ให้ u = 5x แล้ว u เข้าใกล้ศูนย์ และ sin(u)/u เข้าใกล้ 1 เมื่อใช้เรเดียน The answer is $5/2$. คำตอบคือ $5/2$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Foundation $$\\lim_{x\\to0}\\frac{\\sin5x}{2x}$$ Step-by-step solution Rewrite as $\\frac52\\frac{\\sin5x}{5x}$. Let u = 5x. Then u tends to zero and sin(u)/u tends to",
    "previewTh": "พื้นฐาน เฉลยทีละขั้นตอน เขียนเป็น $\\frac52\\frac{\\sin5x}{5x}$ ให้ u = 5x แล้ว u เข้าใกล้ศูนย์ และ sin(u)/u เข้าใกล้ 1 เมื่อใช้เรเดียน คำตอบคือ $5/2$ ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#limits-6",
    "en": "06. Dominant powers",
    "th": "พจน์กำลังสูงสุด",
    "text": "Foundation พื้นฐาน 06. Dominant powers พจน์กำลังสูงสุด $$\\lim_{x\\to\\infty}\\frac{3x^2-x+2}{2x^2+5}$$ Step-by-step solution เฉลยทีละขั้นตอน Divide every term by $x^2$. หารทุกพจน์ด้วย $x^2$ The quotient becomes $(3-1/x+2/x^2)/(2+5/x^2)$. ได้ $(3-1/x+2/x^2)/(2+5/x^2)$ The reciprocal terms tend to zero, giving 3/2. พจน์ส่วนกลับเข้าใกล้ศูนย์ จึงได้ 3/2 Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Foundation $$\\lim_{x\\to\\infty}\\frac{3x^2-x+2}{2x^2+5}$$ Step-by-step solution Divide every term by $x^2$. The quotient becomes $(3-1/x+2/x^2)/(2+5/x^2)$. The re",
    "previewTh": "พื้นฐาน เฉลยทีละขั้นตอน หารทุกพจน์ด้วย $x^2$ ได้ $(3-1/x+2/x^2)/(2+5/x^2)$ พจน์ส่วนกลับเข้าใกล้ศูนย์ จึงได้ 3/2 ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#limits-7",
    "en": "07. An absolute-value jump",
    "th": "ค่าสัมบูรณ์กับการกระโดด",
    "text": "Core ประยุกต์ 07. An absolute-value jump ค่าสัมบูรณ์กับการกระโดด $$\\lim_{x\\to0}\\frac{|x|}{x}$$ Step-by-step solution เฉลยทีละขั้นตอน For x > 0, |x|/x = 1, so the right-hand limit is 1. เมื่อ x > 0 จะมี |x|/x = 1 ลิมิตขวาจึงเป็น 1 For x < 0, |x| = −x, so the left-hand limit is −1. เมื่อ x < 0 จะมี |x| = −x ลิมิตซ้ายจึงเป็น −1 The sides disagree: the two-sided limit does not exist. ทั้งสองด้านไม่เท่ากัน จึงไม่มีลิมิตสองด้าน Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$\\lim_{x\\to0}\\frac{|x|}{x}$$ Step-by-step solution For x > 0, |x|/x = 1, so the right-hand limit is 1. For x < 0, |x| = −x, so the left-hand limit is −1. ",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน เมื่อ x > 0 จะมี |x|/x = 1 ลิมิตขวาจึงเป็น 1 เมื่อ x < 0 จะมี |x| = −x ลิมิตซ้ายจึงเป็น −1 ทั้งสองด้านไม่เท่ากัน จึงไม่มีลิมิตสองด้าน ท"
  },
  {
    "url": "practice.html#limits-8",
    "en": "08. Squeezed oscillation",
    "th": "การแกว่งที่ถูกบีบ",
    "text": "Core ประยุกต์ 08. Squeezed oscillation การแกว่งที่ถูกบีบ $$\\lim_{x\\to0}x\\sin(1/x)$$ Step-by-step solution เฉลยทีละขั้นตอน Use $|\\sin(1/x)|\\le1$ for $x\\ne0$. ใช้ $|\\sin(1/x)|\\le1$ เมื่อ $x\\ne0$ Then $-|x|\\le x\\sin(1/x)\\le|x|$. จึงได้ $-|x|\\le x\\sin(1/x)\\le|x|$ Both bounds tend to zero. The squeeze theorem gives 0. ขอบทั้งสองเข้าใกล้ศูนย์ ทฤษฎีบทบีบจึงให้คำตอบ 0 Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$\\lim_{x\\to0}x\\sin(1/x)$$ Step-by-step solution Use $|\\sin(1/x)|\\le1$ for $x\\ne0$. Then $-|x|\\le x\\sin(1/x)\\le|x|$. Both bounds tend to zero. The squeeze ",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน ใช้ $|\\sin(1/x)|\\le1$ เมื่อ $x\\ne0$ จึงได้ $-|x|\\le x\\sin(1/x)\\le|x|$ ขอบทั้งสองเข้าใกล้ศูนย์ ทฤษฎีบทบีบจึงให้คำตอบ 0 ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#limits-9",
    "en": "09. Exponential remainder",
    "th": "พจน์เหลือของเอ็กซ์โพเนนเชียล",
    "text": "Core ประยุกต์ 09. Exponential remainder พจน์เหลือของเอ็กซ์โพเนนเชียล $$\\lim_{x\\to0}\\frac{e^x-1-x}{x^2}$$ Step-by-step solution เฉลยทีละขั้นตอน Substitution gives 0/0. Both functions are differentiable and the denominator derivative is nonzero near zero, excluding zero. แทนค่าได้ 0/0 ทั้งสองฟังก์ชันหาอนุพันธ์ได้ และอนุพันธ์ตัวส่วนไม่เป็นศูนย์ใกล้ศูนย์เมื่อยกเว้นศูนย์ Apply L’Hôpital: $(e^x-1)/(2x)$, still 0/0. ใช้โลปิตาลได้ $(e^x-1)/(2x)$ ซึ่งยังเป็น 0/0 Apply again: $e^x/2\\to1/2$. ใช้อีกครั้งได้ $e^x/2\\to1/2$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$\\lim_{x\\to0}\\frac{e^x-1-x}{x^2}$$ Step-by-step solution Substitution gives 0/0. Both functions are differentiable and the denominator derivative is nonze",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน แทนค่าได้ 0/0 ทั้งสองฟังก์ชันหาอนุพันธ์ได้ และอนุพันธ์ตัวส่วนไม่เป็นศูนย์ใกล้ศูนย์เมื่อยกเว้นศูนย์ ใช้โลปิตาลได้ $(e^x-1)/(2x)$ ซึ่งยัง"
  },
  {
    "url": "practice.html#limits-10",
    "en": "10. Fill a removable hole",
    "th": "เติมค่าที่จุดขาด",
    "text": "Core ประยุกต์ 10. Fill a removable hole เติมค่าที่จุดขาด $$f(x)=\\begin{cases}(x^2-1)/(x-1)&x\\ne1\\\\k&x=1\\end{cases}$$ Step-by-step solution เฉลยทีละขั้นตอน Find k that makes f continuous at 1. Factor the numerator when x ≠ 1. หา k ที่ทำให้ f ต่อเนื่องที่ 1 แยกตัวประกอบตัวเศษเมื่อ x ≠ 1 The nearby formula simplifies to x + 1, whose limit at 1 is 2. สูตรรอบจุดลดรูปเป็น x + 1 ซึ่งมีลิมิตที่ 1 เท่ากับ 2 Continuity requires f(1) = lim f(x), so k = 2. ความต่อเนื่องต้องมี f(1) = lim f(x) จึงได้ k = 2 Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$f(x)=\\begin{cases}(x^2-1)/(x-1)&x\\ne1\\\\k&x=1\\end{cases}$$ Step-by-step solution Find k that makes f continuous at 1. Factor the numerator when x ≠ 1. The",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน หา k ที่ทำให้ f ต่อเนื่องที่ 1 แยกตัวประกอบตัวเศษเมื่อ x ≠ 1 สูตรรอบจุดลดรูปเป็น x + 1 ซึ่งมีลิมิตที่ 1 เท่ากับ 2 ความต่อเนื่องต้องมี f"
  },
  {
    "url": "practice.html#limits-11",
    "en": "11. Choose delta",
    "th": "เลือกเดลตา",
    "text": "Challenge ท้าทาย 11. Choose delta เลือกเดลตา Prove using the ε–δ definition: พิสูจน์ด้วยนิยาม ε–δ: $$\\lim_{x\\to1}(4x-2)=2$$ Step-by-step solution เฉลยทีละขั้นตอน Let ε > 0 be arbitrary. The output error is |(4x−2)−2| = 4|x−1|. ให้ ε > 0 เป็นจำนวนใด ๆ ความคลาดเคลื่อนคือ |(4x−2)−2| = 4|x−1| Choose δ = ε/4. For every x with 0 < |x−1| < δ, multiply by 4. เลือก δ = ε/4 สำหรับทุก x ที่ 0 < |x−1| < δ ให้คูณด้วย 4 Then |(4x−2)−2| < 4δ = ε. This is exactly the definition of the limit. ได้ |(4x−2)−2| < 4δ = ε ตรงตามนิยามลิมิต Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Challenge Prove using the ε–δ definition: $$\\lim_{x\\to1}(4x-2)=2$$ Step-by-step solution Let ε > 0 be arbitrary. The output error is |(4x−2)−2| = 4|x−1|. Choose",
    "previewTh": "ท้าทาย พิสูจน์ด้วยนิยาม ε–δ: เฉลยทีละขั้นตอน ให้ ε > 0 เป็นจำนวนใด ๆ ความคลาดเคลื่อนคือ |(4x−2)−2| = 4|x−1| เลือก δ = ε/4 สำหรับทุก x ที่ 0 < |x−1| < δ ให้คูณด้"
  },
  {
    "url": "practice.html#limits-12",
    "en": "12. A logarithmic product",
    "th": "ผลคูณลอการิทึม",
    "text": "Challenge ท้าทาย 12. A logarithmic product ผลคูณลอการิทึม $$\\lim_{x\\to0^+}x\\ln x$$ Step-by-step solution เฉลยทีละขั้นตอน The form 0·(−∞) is indeterminate; rewrite it as ln(x)/(1/x). รูป 0·(−∞) ไม่กำหนด ให้เขียนเป็น ln(x)/(1/x) Apply L’Hôpital to get $(1/x)/(-1/x^2)=-x$. ใช้โลปิตาลได้ $(1/x)/(-1/x^2)=-x$ As x approaches zero from the right, −x tends to zero. Answer: 0. เมื่อ x เข้าใกล้ศูนย์ด้านขวา −x เข้าใกล้ศูนย์ คำตอบคือ 0 Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Challenge $$\\lim_{x\\to0^+}x\\ln x$$ Step-by-step solution The form 0·(−∞) is indeterminate; rewrite it as ln(x)/(1/x). Apply L’Hôpital to get $(1/x)/(-1/x^2)=-x$",
    "previewTh": "ท้าทาย เฉลยทีละขั้นตอน รูป 0·(−∞) ไม่กำหนด ให้เขียนเป็น ln(x)/(1/x) ใช้โลปิตาลได้ $(1/x)/(-1/x^2)=-x$ เมื่อ x เข้าใกล้ศูนย์ด้านขวา −x เข้าใกล้ศูนย์ คำตอบคือ 0 ท"
  },
  {
    "url": "practice.html#derivatives-practice",
    "en": "Derivatives",
    "th": "อนุพันธ์",
    "text": "Derivatives อนุพันธ์",
    "previewEn": "",
    "previewTh": ""
  },
  {
    "url": "practice.html#derivatives-1",
    "en": "Derivatives practice 1",
    "th": "อนุพันธ์ 1",
    "text": "Derivative · Easy อนุพันธ์ · พื้นฐาน $$\\frac{d}{dx}(4x^5-3x^2+7)$$ Step-by-step solution เฉลยทีละขั้นตอน Apply the power rule to each term. The derivative of 4x⁵ is 20x⁴, of −3x² is −6x, and of the constant 7 is zero. Combine the terms below. ใช้กฎยกกำลังทีละพจน์ อนุพันธ์ของ 4x⁵ คือ 20x⁴ ของ −3x² คือ −6x และของค่าคงที่ 7 เป็นศูนย์ รวมพจน์ดังด้านล่าง $$20x^4-6x$$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Derivative · Easy $$\\frac{d}{dx}(4x^5-3x^2+7)$$ Step-by-step solution Apply the power rule to each term. The derivative of 4x⁵ is 20x⁴, of −3x² is −6x, and of t",
    "previewTh": "อนุพันธ์ · พื้นฐาน เฉลยทีละขั้นตอน ใช้กฎยกกำลังทีละพจน์ อนุพันธ์ของ 4x⁵ คือ 20x⁴ ของ −3x² คือ −6x และของค่าคงที่ 7 เป็นศูนย์ รวมพจน์ดังด้านล่าง ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#derivatives-2",
    "en": "Derivatives practice 2",
    "th": "อนุพันธ์ 2",
    "text": "Derivative · Chain rule อนุพันธ์ · กฎลูกโซ่ $$\\frac{d}{dx}\\sin(x^2+1)$$ Step-by-step solution เฉลยทีละขั้นตอน Outer derivative: cosine. Inner derivative: $2x$. อนุพันธ์ฟังก์ชันชั้นนอกคือ cosine และชั้นในคือ $2x$ $$2x\\cos(x^2+1)$$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Derivative · Chain rule $$\\frac{d}{dx}\\sin(x^2+1)$$ Step-by-step solution Outer derivative: cosine. Inner derivative: $2x$. $$2x\\cos(x^2+1)$$ Mark as completed",
    "previewTh": "อนุพันธ์ · กฎลูกโซ่ เฉลยทีละขั้นตอน อนุพันธ์ฟังก์ชันชั้นนอกคือ cosine และชั้นในคือ $2x$ ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#derivatives-3",
    "en": "Derivatives practice 3",
    "th": "อนุพันธ์ 3",
    "text": "Derivative · Optimization อนุพันธ์ · ค่าสุดขั้ว Find the maximum value of $f(x)=-x^2+8x-5$. หาค่าสูงสุดของ $f(x)=-x^2+8x-5$ Step-by-step solution เฉลยทีละขั้นตอน $$f'(x)=-2x+8=0\\Rightarrow x=4$$ $$f(4)=-16+32-5=11$$ Since $f''(x)=-2<0$, the maximum value is $11$. เพราะ $f''(x)=-2<0$ ค่าสูงสุดคือ $11$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Derivative · Optimization Find the maximum value of $f(x)=-x^2+8x-5$. Step-by-step solution $$f'(x)=-2x+8=0\\Rightarrow x=4$$ $$f(4)=-16+32-5=11$$ Since $f''(x)=",
    "previewTh": "อนุพันธ์ · ค่าสุดขั้ว หาค่าสูงสุดของ $f(x)=-x^2+8x-5$ เฉลยทีละขั้นตอน เพราะ $f''(x)=-2<0$ ค่าสูงสุดคือ $11$ ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#derivatives-4",
    "en": "04. Product rule",
    "th": "กฎผลคูณ",
    "text": "Core ประยุกต์ 04. Product rule กฎผลคูณ $$\\frac{d}{dx}(x^2e^x)$$ Step-by-step solution เฉลยทีละขั้นตอน Set u = x² and v = eˣ. Then u′ = 2x and v′ = eˣ. ให้ u = x² และ v = eˣ จะได้ u′ = 2x และ v′ = eˣ Use (uv)′ = u′v + uv′: 2xeˣ + x²eˣ. ใช้ (uv)′ = u′v + uv′ ได้ 2xeˣ + x²eˣ Factor to obtain eˣ(x² + 2x). ดึงตัวประกอบได้ eˣ(x² + 2x) Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$\\frac{d}{dx}(x^2e^x)$$ Step-by-step solution Set u = x² and v = eˣ. Then u′ = 2x and v′ = eˣ. Use (uv)′ = u′v + uv′: 2xeˣ + x²eˣ. Factor to obtain eˣ(x² ",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน ให้ u = x² และ v = eˣ จะได้ u′ = 2x และ v′ = eˣ ใช้ (uv)′ = u′v + uv′ ได้ 2xeˣ + x²eˣ ดึงตัวประกอบได้ eˣ(x² + 2x) ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#derivatives-5",
    "en": "05. Quotient rule",
    "th": "กฎผลหาร",
    "text": "Core ประยุกต์ 05. Quotient rule กฎผลหาร $$\\frac{d}{dx}\\frac{x^2+1}{x-1}$$ Step-by-step solution เฉลยทีละขั้นตอน The domain excludes x = 1. Set u = x²+1, v = x−1. โดเมนไม่รวม x = 1 ให้ u = x²+1, v = x−1 Use $(u^{\\prime} v-uv^{\\prime})/v^2=[2x(x-1)-(x^2+1)]/(x-1)^2$. ใช้ $(u^{\\prime} v-uv^{\\prime})/v^2=[2x(x-1)-(x^2+1)]/(x-1)^2$ Simplify: $(x^2-2x-1)/(x-1)^2$, for $x\\ne1$. จัดรูปได้ $(x^2-2x-1)/(x-1)^2$ เมื่อ $x\\ne1$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$\\frac{d}{dx}\\frac{x^2+1}{x-1}$$ Step-by-step solution The domain excludes x = 1. Set u = x²+1, v = x−1. Use $(u^{\\prime} v-uv^{\\prime})/v^2=[2x(x-1)-(x^2",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน โดเมนไม่รวม x = 1 ให้ u = x²+1, v = x−1 ใช้ $(u^{\\prime} v-uv^{\\prime})/v^2=[2x(x-1)-(x^2+1)]/(x-1)^2$ จัดรูปได้ $(x^2-2x-1)/(x-1)^2$ เ"
  },
  {
    "url": "practice.html#derivatives-6",
    "en": "06. Logarithmic chain",
    "th": "ลูกโซ่ลอการิทึม",
    "text": "Core ประยุกต์ 06. Logarithmic chain ลูกโซ่ลอการิทึม $$\\frac{d}{dx}\\ln(1+x^2)$$ Step-by-step solution เฉลยทีละขั้นตอน The inner function 1+x² is positive for all real x. ฟังก์ชันชั้นใน 1+x² เป็นบวกสำหรับ x จริงทุกค่า Differentiate ln u to get u′/u; here u′ = 2x. หาอนุพันธ์ ln u ได้ u′/u โดย u′ = 2x The derivative is $2x/(1+x^2)$. อนุพันธ์คือ $2x/(1+x^2)$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$\\frac{d}{dx}\\ln(1+x^2)$$ Step-by-step solution The inner function 1+x² is positive for all real x. Differentiate ln u to get u′/u; here u′ = 2x. The deri",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน ฟังก์ชันชั้นใน 1+x² เป็นบวกสำหรับ x จริงทุกค่า หาอนุพันธ์ ln u ได้ u′/u โดย u′ = 2x อนุพันธ์คือ $2x/(1+x^2)$ ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#derivatives-7",
    "en": "07. Tangent to a circle",
    "th": "เส้นสัมผัสวงกลม",
    "text": "Core ประยุกต์ 07. Tangent to a circle เส้นสัมผัสวงกลม $$x^2+y^2=25,\\quad (x,y)=(3,4)$$ Step-by-step solution เฉลยทีละขั้นตอน Differentiate implicitly: 2x + 2yy′ = 0. หาอนุพันธ์โดยปริยาย: 2x + 2yy′ = 0 Solve y′ = −x/y and substitute (3,4): slope = −3/4. แก้ได้ y′ = −x/y แล้วแทน (3,4) ความชันคือ −3/4 The tangent line is $y-4=-\\frac34(x-3)$. เส้นสัมผัสคือ $y-4=-\\frac34(x-3)$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$x^2+y^2=25,\\quad (x,y)=(3,4)$$ Step-by-step solution Differentiate implicitly: 2x + 2yy′ = 0. Solve y′ = −x/y and substitute (3,4): slope = −3/4. The tan",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน หาอนุพันธ์โดยปริยาย: 2x + 2yy′ = 0 แก้ได้ y′ = −x/y แล้วแทน (3,4) ความชันคือ −3/4 เส้นสัมผัสคือ $y-4=-\\frac34(x-3)$ ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#derivatives-8",
    "en": "08. Variable exponent",
    "th": "เลขชี้กำลังตัวแปร",
    "text": "Challenge ท้าทาย 08. Variable exponent เลขชี้กำลังตัวแปร $$\\frac{d}{dx}x^x,\\quad x>0$$ Step-by-step solution เฉลยทีละขั้นตอน Let y = xˣ and take logs: ln y = x ln x. ให้ y = xˣ แล้วใช้ลอการิทึม: ln y = x ln x Differentiate: y′/y = ln x + 1. หาอนุพันธ์: y′/y = ln x + 1 Multiply by y = xˣ: y′ = xˣ(ln x + 1). คูณด้วย y = xˣ ได้ y′ = xˣ(ln x + 1) Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Challenge $$\\frac{d}{dx}x^x,\\quad x>0$$ Step-by-step solution Let y = xˣ and take logs: ln y = x ln x. Differentiate: y′/y = ln x + 1. Multiply by y = xˣ: y′ = ",
    "previewTh": "ท้าทาย เฉลยทีละขั้นตอน ให้ y = xˣ แล้วใช้ลอการิทึม: ln y = x ln x หาอนุพันธ์: y′/y = ln x + 1 คูณด้วย y = xˣ ได้ y′ = xˣ(ln x + 1) ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#derivatives-9",
    "en": "09. Closed-interval extrema",
    "th": "ค่าสุดขั้วบนช่วงปิด",
    "text": "Challenge ท้าทาย 09. Closed-interval extrema ค่าสุดขั้วบนช่วงปิด $$f(x)=x^3-3x,\\quad x\\in[-2,2]$$ Step-by-step solution เฉลยทีละขั้นตอน Continuity guarantees global extrema. Solve f′ = 3x²−3 = 0 to find x = ±1. ความต่อเนื่องรับประกันค่าสุดขั้วสัมบูรณ์ แก้ f′ = 3x²−3 = 0 ได้ x = ±1 Evaluate at both critical points and endpoints: f(−2)=−2, f(−1)=2, f(1)=−2, f(2)=2. คำนวณทั้งจุดวิกฤตและปลายช่วง: f(−2)=−2, f(−1)=2, f(1)=−2, f(2)=2 Maximum 2 at −1 and 2; minimum −2 at −2 and 1. ค่าสูงสุด 2 ที่ −1 และ 2 ค่าต่ำสุด −2 ที่ −2 และ 1 Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Challenge $$f(x)=x^3-3x,\\quad x\\in[-2,2]$$ Step-by-step solution Continuity guarantees global extrema. Solve f′ = 3x²−3 = 0 to find x = ±1. Evaluate at both cri",
    "previewTh": "ท้าทาย เฉลยทีละขั้นตอน ความต่อเนื่องรับประกันค่าสุดขั้วสัมบูรณ์ แก้ f′ = 3x²−3 = 0 ได้ x = ±1 คำนวณทั้งจุดวิกฤตและปลายช่วง: f(−2)=−2, f(−1)=2, f(1)=−2, f(2)=2 ค"
  },
  {
    "url": "practice.html#derivatives-10",
    "en": "10. Mean value point",
    "th": "จุดค่ากลาง",
    "text": "Core ประยุกต์ 10. Mean value point จุดค่ากลาง $$f(x)=x^2,\\quad [1,3]$$ Step-by-step solution เฉลยทีละขั้นตอน The function is continuous on [1,3] and differentiable on (1,3), so the MVT applies. ฟังก์ชันต่อเนื่องบน [1,3] และหาอนุพันธ์ได้บน (1,3) จึงใช้ทฤษฎีบทค่ากลางได้ The average slope is (9−1)/(3−1) = 4. ความชันเฉลี่ยคือ (9−1)/(3−1) = 4 Solve f′(c) = 2c = 4 to obtain c = 2, inside the interval. แก้ f′(c) = 2c = 4 ได้ c = 2 ซึ่งอยู่ภายในช่วง Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$f(x)=x^2,\\quad [1,3]$$ Step-by-step solution The function is continuous on [1,3] and differentiable on (1,3), so the MVT applies. The average slope is (9",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน ฟังก์ชันต่อเนื่องบน [1,3] และหาอนุพันธ์ได้บน (1,3) จึงใช้ทฤษฎีบทค่ากลางได้ ความชันเฉลี่ยคือ (9−1)/(3−1) = 4 แก้ f′(c) = 2c = 4 ได้ c = "
  },
  {
    "url": "practice.html#derivatives-11",
    "en": "11. Related rates: sphere",
    "th": "อัตราสัมพัทธ์: ทรงกลม",
    "text": "Challenge ท้าทาย 11. Related rates: sphere อัตราสัมพัทธ์: ทรงกลม $$V=\\frac43\\pi r^3,\\quad r=3\\;\\mathrm{cm},\\quad \\frac{dr}{dt}=2\\;\\mathrm{cm/s}$$ Step-by-step solution เฉลยทีละขั้นตอน Differentiate the volume formula with respect to time before substituting the radius. หาอนุพันธ์สูตรปริมาตรเทียบกับเวลาก่อนแทนรัศมี $dV/dt=4\\pi r^2\\,dr/dt$. $dV/dt=4\\pi r^2\\,dr/dt$ Substitute: $4\\pi(3)^2(2)=72\\pi\\;\\mathrm{cm^3/s}$. แทนค่า: $4\\pi(3)^2(2)=72\\pi\\;\\mathrm{cm^3/s}$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Challenge $$V=\\frac43\\pi r^3,\\quad r=3\\;\\mathrm{cm},\\quad \\frac{dr}{dt}=2\\;\\mathrm{cm/s}$$ Step-by-step solution Differentiate the volume formula with respect t",
    "previewTh": "ท้าทาย เฉลยทีละขั้นตอน หาอนุพันธ์สูตรปริมาตรเทียบกับเวลาก่อนแทนรัศมี $dV/dt=4\\pi r^2\\,dr/dt$ แทนค่า: $4\\pi(3)^2(2)=72\\pi\\;\\mathrm{cm^3/s}$ ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#derivatives-12",
    "en": "12. Local approximation",
    "th": "การประมาณใกล้จุด",
    "text": "Foundation พื้นฐาน 12. Local approximation การประมาณใกล้จุด Approximate using the tangent at x = 4: ประมาณด้วยเส้นสัมผัสที่ x = 4: $$\\sqrt{4.1}$$ Step-by-step solution เฉลยทีละขั้นตอน Choose f(x) = √x. At a = 4, f(a) = 2 and f′(a) = 1/4. เลือก f(x) = √x ที่ a = 4 มี f(a) = 2 และ f′(a) = 1/4 Build L(x) = 2 + (x−4)/4. สร้าง L(x) = 2 + (x−4)/4 L(4.1) = 2.025. This is an approximation; concavity down means the tangent overestimates. L(4.1) = 2.025 เป็นค่าประมาณ กราฟเว้าลงจึงได้ค่ามากกว่าค่าจริง Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Foundation Approximate using the tangent at x = 4: $$\\sqrt{4.1}$$ Step-by-step solution Choose f(x) = √x. At a = 4, f(a) = 2 and f′(a) = 1/4. Build L(x) = 2 + (",
    "previewTh": "พื้นฐาน ประมาณด้วยเส้นสัมผัสที่ x = 4: เฉลยทีละขั้นตอน เลือก f(x) = √x ที่ a = 4 มี f(a) = 2 และ f′(a) = 1/4 สร้าง L(x) = 2 + (x−4)/4 L(4.1) = 2.025 เป็นค่าประม"
  },
  {
    "url": "practice.html#integrals-practice",
    "en": "Integrals",
    "th": "ปริพันธ์",
    "text": "Integrals ปริพันธ์",
    "previewEn": "",
    "previewTh": ""
  },
  {
    "url": "practice.html#integrals-1",
    "en": "Integrals practice 1",
    "th": "ปริพันธ์ 1",
    "text": "Integral · Easy ปริพันธ์ · พื้นฐาน $$\\int(6x^2-4x+3)dx$$ Step-by-step solution เฉลยทีละขั้นตอน Integrate term by term: increase each power by one and divide by the new power. This gives 6x³/3 − 4x²/2 + 3x. Add an arbitrary constant C. อินทิเกรตทีละพจน์ เพิ่มเลขชี้กำลังหนึ่งแล้วหารด้วยกำลังใหม่ ได้ 6x³/3 − 4x²/2 + 3x แล้วบวกค่าคงที่ C $$2x^3-2x^2+3x+C$$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Integral · Easy $$\\int(6x^2-4x+3)dx$$ Step-by-step solution Integrate term by term: increase each power by one and divide by the new power. This gives 6x³/3 − 4",
    "previewTh": "ปริพันธ์ · พื้นฐาน เฉลยทีละขั้นตอน อินทิเกรตทีละพจน์ เพิ่มเลขชี้กำลังหนึ่งแล้วหารด้วยกำลังใหม่ ได้ 6x³/3 − 4x²/2 + 3x แล้วบวกค่าคงที่ C ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#integrals-2",
    "en": "Integrals practice 2",
    "th": "ปริพันธ์ 2",
    "text": "Integral · Substitution ปริพันธ์ · การแทนค่า $$\\int 2x e^{x^2}dx$$ Step-by-step solution เฉลยทีละขั้นตอน Let $u=x^2$, $du=2x\\,dx$. ให้ $u=x^2$, $du=2x\\,dx$ $$\\int e^u du=e^u+C=e^{x^2}+C$$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Integral · Substitution $$\\int 2x e^{x^2}dx$$ Step-by-step solution Let $u=x^2$, $du=2x\\,dx$. $$\\int e^u du=e^u+C=e^{x^2}+C$$ Mark as completed",
    "previewTh": "ปริพันธ์ · การแทนค่า เฉลยทีละขั้นตอน ให้ $u=x^2$, $du=2x\\,dx$ ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#integrals-3",
    "en": "Integrals practice 3",
    "th": "ปริพันธ์ 3",
    "text": "Integral · Definite ปริพันธ์ · จำกัดเขต $$\\int_0^2(3x^2+1)dx$$ Step-by-step solution เฉลยทีละขั้นตอน An antiderivative of 3x² + 1 is x³ + x. Use the FTC: evaluate at 2, then subtract its value at 0. Both bounds lie in the continuous domain. ปฏิยานุพันธ์ของ 3x² + 1 คือ x³ + x ใช้ทฤษฎีบทมูลฐาน แทน 2 แล้วลบค่าที่ 0 ขอบทั้งสองอยู่ในโดเมนที่ต่อเนื่อง $$\\left[x^3+x\\right]_0^2=8+2=10$$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Integral · Definite $$\\int_0^2(3x^2+1)dx$$ Step-by-step solution An antiderivative of 3x² + 1 is x³ + x. Use the FTC: evaluate at 2, then subtract its value at ",
    "previewTh": "ปริพันธ์ · จำกัดเขต เฉลยทีละขั้นตอน ปฏิยานุพันธ์ของ 3x² + 1 คือ x³ + x ใช้ทฤษฎีบทมูลฐาน แทน 2 แล้วลบค่าที่ 0 ขอบทั้งสองอยู่ในโดเมนที่ต่อเนื่อง ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#integrals-4",
    "en": "04. Integration by parts",
    "th": "อินทิเกรตโดยส่วน",
    "text": "Core ประยุกต์ 04. Integration by parts อินทิเกรตโดยส่วน $$\\int xe^x\\,dx$$ Step-by-step solution เฉลยทีละขั้นตอน Choose u = x and dv = eˣ dx, so du = dx and v = eˣ. เลือก u = x และ dv = eˣ dx จึงได้ du = dx และ v = eˣ Use $\\int u\\,dv=uv-\\int v\\,du$ to get $xe^x-\\int e^x dx$. ใช้ $\\int u\\,dv=uv-\\int v\\,du$ ได้ $xe^x-\\int e^x dx$ The result is eˣ(x−1) + C. Differentiate it to check: xeˣ. ผลคือ eˣ(x−1) + C หาอนุพันธ์ตรวจสอบได้ xeˣ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$\\int xe^x\\,dx$$ Step-by-step solution Choose u = x and dv = eˣ dx, so du = dx and v = eˣ. Use $\\int u\\,dv=uv-\\int v\\,du$ to get $xe^x-\\int e^x dx$. The r",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน เลือก u = x และ dv = eˣ dx จึงได้ du = dx และ v = eˣ ใช้ $\\int u\\,dv=uv-\\int v\\,du$ ได้ $xe^x-\\int e^x dx$ ผลคือ eˣ(x−1) + C หาอนุพันธ์"
  },
  {
    "url": "practice.html#integrals-5",
    "en": "05. Recognize a logarithm",
    "th": "มองหารูปลอการิทึม",
    "text": "Core ประยุกต์ 05. Recognize a logarithm มองหารูปลอการิทึม $$\\int\\frac{2x}{1+x^2}\\,dx$$ Step-by-step solution เฉลยทีละขั้นตอน Set u = 1+x², so du = 2x dx. ให้ u = 1+x² จึงได้ du = 2x dx The integral becomes $\\int du/u=\\ln|u|+C$. ปริพันธ์เป็น $\\int du/u=\\ln|u|+C$ Since 1+x² > 0, the answer is ln(1+x²) + C. เพราะ 1+x² > 0 คำตอบคือ ln(1+x²) + C Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$\\int\\frac{2x}{1+x^2}\\,dx$$ Step-by-step solution Set u = 1+x², so du = 2x dx. The integral becomes $\\int du/u=\\ln|u|+C$. Since 1+x² > 0, the answer is ln",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน ให้ u = 1+x² จึงได้ du = 2x dx ปริพันธ์เป็น $\\int du/u=\\ln|u|+C$ เพราะ 1+x² > 0 คำตอบคือ ln(1+x²) + C ทำข้อนี้แล้ว"
  },
  {
    "url": "practice.html#integrals-6",
    "en": "06. Trigonometric power",
    "th": "กำลังตรีโกณมิติ",
    "text": "Core ประยุกต์ 06. Trigonometric power กำลังตรีโกณมิติ $$\\int\\sin^2x\\,dx$$ Step-by-step solution เฉลยทีละขั้นตอน Use the identity sin²x = (1−cos 2x)/2. ใช้เอกลักษณ์ sin²x = (1−cos 2x)/2 Integrate the constant term as x/2. The cosine term needs a factor 1/2 from its inner derivative. อินทิเกรตพจน์คงที่ได้ x/2 พจน์ cosine ต้องคูณ 1/2 จากอนุพันธ์ชั้นใน The answer is $x/2-\\sin(2x)/4+C$. คำตอบคือ $x/2-\\sin(2x)/4+C$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$\\int\\sin^2x\\,dx$$ Step-by-step solution Use the identity sin²x = (1−cos 2x)/2. Integrate the constant term as x/2. The cosine term needs a factor 1/2 fro",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน ใช้เอกลักษณ์ sin²x = (1−cos 2x)/2 อินทิเกรตพจน์คงที่ได้ x/2 พจน์ cosine ต้องคูณ 1/2 จากอนุพันธ์ชั้นใน คำตอบคือ $x/2-\\sin(2x)/4+C$ ทำข้อ"
  },
  {
    "url": "practice.html#integrals-7",
    "en": "07. Partial fractions",
    "th": "เศษส่วนย่อย",
    "text": "Challenge ท้าทาย 07. Partial fractions เศษส่วนย่อย $$\\int\\frac{dx}{x^2-1}$$ Step-by-step solution เฉลยทีละขั้นตอน Factor the denominator: $(x-1)(x+1)$, excluding $x=\\pm1$. แยกตัวส่วนเป็น $(x-1)(x+1)$ โดยไม่รวม $x=\\pm1$ Solve $1=A(x+1)+B(x-1)$: $A=1/2$, $B=-1/2$. แก้ $1=A(x+1)+B(x-1)$ ได้ $A=1/2$, $B=-1/2$ Integrate: $\\frac12\\ln|x-1|-\\frac12\\ln|x+1|+C$, on each interval of the domain. อินทิเกรตได้ $\\frac12\\ln|x-1|-\\frac12\\ln|x+1|+C$ แยกในแต่ละช่วงของโดเมน Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Challenge $$\\int\\frac{dx}{x^2-1}$$ Step-by-step solution Factor the denominator: $(x-1)(x+1)$, excluding $x=\\pm1$. Solve $1=A(x+1)+B(x-1)$: $A=1/2$, $B=-1/2$. I",
    "previewTh": "ท้าทาย เฉลยทีละขั้นตอน แยกตัวส่วนเป็น $(x-1)(x+1)$ โดยไม่รวม $x=\\pm1$ แก้ $1=A(x+1)+B(x-1)$ ได้ $A=1/2$, $B=-1/2$ อินทิเกรตได้ $\\frac12\\ln|x-1|-\\frac12\\ln|x+1|+"
  },
  {
    "url": "practice.html#integrals-8",
    "en": "08. Signed integral versus area",
    "th": "ปริพันธ์แบบมีเครื่องหมายกับพื้นที่",
    "text": "Foundation พื้นฐาน 08. Signed integral versus area ปริพันธ์แบบมีเครื่องหมายกับพื้นที่ $$f(x)=x,\\quad [-1,1]$$ Step-by-step solution เฉลยทีละขั้นตอน The signed integral is $[x^2/2]_{-1}^1=0$. ปริพันธ์แบบมีเครื่องหมายคือ $[x^2/2]_{-1}^1=0$ For geometric area, split at zero and negate the part below the axis. สำหรับพื้นที่เรขาคณิต ให้แบ่งที่ศูนย์แล้วเปลี่ยนเครื่องหมายส่วนใต้แกน $A=-\\int_{-1}^0x\\,dx+\\int_0^1x\\,dx=1/2+1/2=1$. $A=-\\int_{-1}^0x\\,dx+\\int_0^1x\\,dx=1/2+1/2=1$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Foundation $$f(x)=x,\\quad [-1,1]$$ Step-by-step solution The signed integral is $[x^2/2]_{-1}^1=0$. For geometric area, split at zero and negate the part below ",
    "previewTh": "พื้นฐาน เฉลยทีละขั้นตอน ปริพันธ์แบบมีเครื่องหมายคือ $[x^2/2]_{-1}^1=0$ สำหรับพื้นที่เรขาคณิต ให้แบ่งที่ศูนย์แล้วเปลี่ยนเครื่องหมายส่วนใต้แกน $A=-\\int_{-1}^0x\\,d"
  },
  {
    "url": "practice.html#integrals-9",
    "en": "09. Area between curves",
    "th": "พื้นที่ระหว่างเส้นโค้ง",
    "text": "Core ประยุกต์ 09. Area between curves พื้นที่ระหว่างเส้นโค้ง $$y=x,\\quad y=x^2$$ Step-by-step solution เฉลยทีละขั้นตอน Find intersections from x = x²: x = 0 and x = 1. หาจุดตัดจาก x = x² ได้ x = 0 และ x = 1 On [0,1], x ≥ x². Integrate upper minus lower. บน [0,1] มี x ≥ x² ให้หาปริพันธ์เส้นบนลบเส้นล่าง $A=\\int_0^1(x-x^2)dx=[x^2/2-x^3/3]_0^1=1/6$. $A=\\int_0^1(x-x^2)dx=[x^2/2-x^3/3]_0^1=1/6$ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$y=x,\\quad y=x^2$$ Step-by-step solution Find intersections from x = x²: x = 0 and x = 1. On [0,1], x ≥ x². Integrate upper minus lower. $A=\\int_0^1(x-x^2",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน หาจุดตัดจาก x = x² ได้ x = 0 และ x = 1 บน [0,1] มี x ≥ x² ให้หาปริพันธ์เส้นบนลบเส้นล่าง $A=\\int_0^1(x-x^2)dx=[x^2/2-x^3/3]_0^1=1/6$ ทำข"
  },
  {
    "url": "practice.html#integrals-10",
    "en": "10. Variable upper bound",
    "th": "ขอบบนเป็นตัวแปร",
    "text": "Core ประยุกต์ 10. Variable upper bound ขอบบนเป็นตัวแปร $$\\frac{d}{dx}\\int_0^{x^2}\\cos t\\,dt$$ Step-by-step solution เฉลยทีละขั้นตอน The integrand is continuous, so the FTC applies. ฟังก์ชันใต้ปริพันธ์ต่อเนื่อง จึงใช้ทฤษฎีบทมูลฐานได้ Evaluate the integrand at the upper bound: cos(x²). แทนขอบบนลงในฟังก์ชันใต้ปริพันธ์: cos(x²) Multiply by the upper-bound derivative 2x. Answer: 2x cos(x²). คูณด้วยอนุพันธ์ขอบบน 2x คำตอบคือ 2x cos(x²) Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Core $$\\frac{d}{dx}\\int_0^{x^2}\\cos t\\,dt$$ Step-by-step solution The integrand is continuous, so the FTC applies. Evaluate the integrand at the upper bound: co",
    "previewTh": "ประยุกต์ เฉลยทีละขั้นตอน ฟังก์ชันใต้ปริพันธ์ต่อเนื่อง จึงใช้ทฤษฎีบทมูลฐานได้ แทนขอบบนลงในฟังก์ชันใต้ปริพันธ์: cos(x²) คูณด้วยอนุพันธ์ขอบบน 2x คำตอบคือ 2x cos(x²"
  },
  {
    "url": "practice.html#integrals-11",
    "en": "11. A convergent improper integral",
    "th": "ปริพันธ์ไม่ตรงแบบที่ลู่เข้า",
    "text": "Challenge ท้าทาย 11. A convergent improper integral ปริพันธ์ไม่ตรงแบบที่ลู่เข้า $$\\int_1^{\\infty}\\frac{dx}{x^2}$$ Step-by-step solution เฉลยทีละขั้นตอน Replace infinity by $R$ and plan to take $R\\to\\infty$. แทนอนันต์ด้วย $R$ แล้วเตรียมหาลิมิต $R\\to\\infty$ $\\int_1^R x^{-2}dx=[-1/x]_1^R=1-1/R$. $\\int_1^R x^{-2}dx=[-1/x]_1^R=1-1/R$ The limit is 1, so the improper integral converges to 1. ลิมิตคือ 1 ปริพันธ์ไม่ตรงแบบจึงลู่เข้าเท่ากับ 1 Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Challenge $$\\int_1^{\\infty}\\frac{dx}{x^2}$$ Step-by-step solution Replace infinity by $R$ and plan to take $R\\to\\infty$. $\\int_1^R x^{-2}dx=[-1/x]_1^R=1-1/R$. T",
    "previewTh": "ท้าทาย เฉลยทีละขั้นตอน แทนอนันต์ด้วย $R$ แล้วเตรียมหาลิมิต $R\\to\\infty$ $\\int_1^R x^{-2}dx=[-1/x]_1^R=1-1/R$ ลิมิตคือ 1 ปริพันธ์ไม่ตรงแบบจึงลู่เข้าเท่ากับ 1 ทำข"
  },
  {
    "url": "practice.html#integrals-12",
    "en": "12. A divergent singularity",
    "th": "จุดเอกฐานที่ลู่ออก",
    "text": "Challenge ท้าทาย 12. A divergent singularity จุดเอกฐานที่ลู่ออก $$\\int_{-1}^1\\frac{dx}{x}$$ Step-by-step solution เฉลยทีละขั้นตอน Split at zero, where the integrand is undefined. Each side must converge independently. แบ่งที่ศูนย์ซึ่งฟังก์ชันไม่นิยาม แต่ละด้านต้องลู่เข้าแยกกัน $\\int_\\varepsilon^1dx/x=-\\ln\\varepsilon\\to+\\infty$ as $\\varepsilon\\to0^+$. $\\int_\\varepsilon^1dx/x=-\\ln\\varepsilon\\to+\\infty$ เมื่อ $\\varepsilon\\to0^+$ Already one side diverges, so the improper integral diverges. Symmetric cancellation does not fix it. ด้านเดียวลู่ออกก็สรุปว่าปริพันธ์ลู่ออกได้แล้ว การหักล้างแบบสมมาตรแก้ไม่ได้ Mark as completed ทำข้อนี้แล้ว",
    "previewEn": "Challenge $$\\int_{-1}^1\\frac{dx}{x}$$ Step-by-step solution Split at zero, where the integrand is undefined. Each side must converge independently. $\\int_\\varep",
    "previewTh": "ท้าทาย เฉลยทีละขั้นตอน แบ่งที่ศูนย์ซึ่งฟังก์ชันไม่นิยาม แต่ละด้านต้องลู่เข้าแยกกัน $\\int_\\varepsilon^1dx/x=-\\ln\\varepsilon\\to+\\infty$ เมื่อ $\\varepsilon\\to0^+$ "
  }
];
